/**
 * Las 54 paradas del rutero de ventas del 15 al 17 de septiembre de 2026, con el
 * enlace de su demo. Alimenta la pantalla /rutero, que es desde donde se lanzan
 * las demos cuando Trimly está instalada en el iPad como app a pantalla completa.
 *
 * Generado desde la entrega del rutero; no se edita a mano.
 */
export interface ParadaRutero {
  parada: number;
  bloque: string;
  hora: string;
  nombre: string;
  tipo: string;
  path: string;
}

export const RUTERO: ParadaRutero[] = [
  {
    parada: 1,
    bloque: "M1",
    hora: "10:00",
    nombre: "Barber hamza for men",
    tipo: "Barbería",
    path: "/s/barber-hamza-for-men?d=eyJuIjoiQmFyYmVyIGhhbXphIGZvciBtZW4iLCJ0IjoiQmFyYmVyw61hIiwiZCI6IkMuIEJ1cmd1ZXRlLCAxMCwgTG9jIDUsIEZ1ZW5jYXJyYWwtRWwgUGFyZG8sIDI4MDUwIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI2MzQgMDYgNTcgMzYiLCJyIjo0LjYsImMiOjM5NSwiaCI6Ii9hcGkvZm90bz9wbGFjZT1DaElKTFF3MzU4RXJRZzBSNWM0VWFQVGs3X00maT0yIiwibyI6WyIxMDowMOKAkzE0OjAwLCAxNjowMOKAkzIwOjMwIiwiMTA6MDDigJMxNDowMCwgMTY6MDDigJMyMDozMCIsIjEwOjAw4oCTMTQ6MDAsIDE2OjAw4oCTMjA6MzAiLCIxMDowMOKAkzE0OjAwLCAxNjowMOKAkzIwOjMwIiwiMTA6MDDigJMxNDowMCwgMTY6MDDigJMyMDozMCIsIjEwOjAw4oCTMTY6MDAiLCJDZXJyYWRvIl0sImYiOjEwLCJnIjpbIjEiLCI1IiwiMCIsIjQiXX0",
  },
  {
    parada: 2,
    bloque: "M1",
    hora: "10:20",
    nombre: "Vannity Peluquería- las tablas)",
    tipo: "Peluquería",
    path: "/s/vannity-peluqueria-las-tablas?d=eyJuIjoiVmFubml0eSBQZWx1cXVlcsOtYS0gbGFzIHRhYmxhcykiLCJ0IjoiUGVsdXF1ZXLDrWEiLCJkIjoiQ2FsbGUgQ2FzdGllbGxvIGRlIEphY2EsIGVzcXVpbmEsIEMuIEJ1cmd1ZXRlLCAzOCwgRnVlbmNhcnJhbC1FbCBQYXJkbywgMjgwNTAgTWFkcmlkLCBFc3Bhw7FhIiwicCI6IjkxNSA5OSA0MiA3NCIsInIiOjQuNywiYyI6MzUyLCJoIjoiL2FwaS9mb3RvP3BsYWNlPUNoSUpld1VpTXdZclFnMFJvRXltb0VYUmpSbyZpPTIiLCJvIjpbIjEwOjAw4oCTMjA6MDAiLCIxMDowMOKAkzIwOjAwIiwiMTA6MDDigJMyMDowMCIsIjEwOjAw4oCTMjA6MDAiLCIxMDowMOKAkzIwOjAwIiwiMTA6MDDigJMxODowMCIsIkNlcnJhZG8iXSwiZiI6MTAsImciOlsiMCIsIjEiLCI0IiwiMyJdfQ",
  },
  {
    parada: 3,
    bloque: "M1",
    hora: "10:45",
    nombre: "Artes'll barber shop",
    tipo: "Barbería",
    path: "/s/artes-ll-barber-shop?d=eyJuIjoiQXJ0ZXMnbGwgYmFyYmVyIHNob3AiLCJ0IjoiQmFyYmVyw61hIiwiZCI6IkNhbGxlIGRlIE1hcsOtYSBUdWJhdSwgMTksIEZ1ZW5jYXJyYWwtRWwgUGFyZG8sIDI4MDUwIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTMgNTggODQgNDgiLCJyIjo0LjUsImMiOjc4LCJoIjoiL2FwaS9mb3RvP3BsYWNlPUNoSUpBOUc1bHVzclFnMFJyWTlVdzhWSlRYdyZpPTMiLCJvIjpbIjEwOjAw4oCTMTM6MzAsIDE3OjAw4oCTMjA6MDAiLCIxMDowMOKAkzEzOjMwLCAxNzowMOKAkzIwOjAwIiwiMTA6MDDigJMxMzozMCwgMTc6MDDigJMyMDowMCIsIjEwOjAw4oCTMTM6MzAsIDE3OjAw4oCTMjA6MDAiLCIxMDowMOKAkzEzOjMwLCAxNzowMOKAkzIwOjAwIiwiMTA6MDDigJMxNDowMCIsIkNlcnJhZG8iXSwiZiI6MTAsImciOlsiMiIsIjQiLCIxIiwiNSJdfQ",
  },
  {
    parada: 4,
    bloque: "M1",
    hora: "11:20",
    nombre: "Mas Peluqueros Madrid",
    tipo: "Peluquería",
    path: "/s/mas-peluqueros-madrid?d=eyJuIjoiTWFzIFBlbHVxdWVyb3MgTWFkcmlkIiwidCI6IlBlbHVxdWVyw61hIiwiZCI6IkMuIGRlIFBhbGFzIGRlIFJleSwgMjIsIEZ1ZW5jYXJyYWwtRWwgUGFyZG8sIDI4MDUwIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTcgNTAgNTcgMjMiLCJyIjo0LjUsImMiOjM0NywiaCI6Ii9hcGkvZm90bz9wbGFjZT1DaElKZTh5NENLQXVRZzBSdjZMc2YxbnJuYjQmaT0wIiwibyI6WyI5OjMw4oCTMjA6MDAiLCI5OjMw4oCTMjA6MDAiLCI5OjMw4oCTMjA6MDAiLCI5OjMw4oCTMjA6MDAiLCI5OjMw4oCTMjA6MDAiLCI5OjAw4oCTMTQ6MDAiLCJDZXJyYWRvIl0sImYiOjEwLCJnIjpbIjMiLCIxIiwiMiIsIjUiXX0",
  },
  {
    parada: 5,
    bloque: "M1",
    hora: "11:35",
    nombre: "JF estilistas",
    tipo: "Peluquería",
    path: "/s/jf-estilistas?d=eyJuIjoiSkYgZXN0aWxpc3RhcyIsInQiOiJQZWx1cXVlcsOtYSIsImQiOiJDLiBkZSBQYWxhcyBkZSBSZXksIDE4LCBGdWVuY2FycmFsLUVsIFBhcmRvLCAyODA1MCBNYWRyaWQsIEVzcGHDsWEiLCJwIjoiNjU3IDI1IDEwIDM5IiwiciI6NC42LCJjIjoyMDQsImgiOiIvYXBpL2ZvdG8_cGxhY2U9Q2hJSjNRczhaZmNyUWcwUmVLNTlTTzFxODhJJmk9MiIsIm8iOlsiMTA6MDDigJMyMDowMCIsIjEwOjAw4oCTMjA6MDAiLCIxMDowMOKAkzIwOjAwIiwiMTA6MDDigJMyMDowMCIsIjEwOjAw4oCTMjA6MDAiLCI5OjMw4oCTMTQ6MDAiLCJDZXJyYWRvIl0sImYiOjEwLCJnIjpbIjAiLCIzIiwiMSIsIjUiXX0",
  },
  {
    parada: 6,
    bloque: "M1",
    hora: "12:00",
    nombre: "Saria Style Hair",
    tipo: "Peluquería",
    path: "/s/saria-style-hair?d=eyJuIjoiU2FyaWEgU3R5bGUgSGFpciIsInQiOiJQZWx1cXVlcsOtYSIsImQiOiJDYWxsZSBIb250YW5hcywgQy4gVmlsb3JpYSBkZSBMYSBSaW9qYSwgRXNxdWluYSwgRnVlbmNhcnJhbC1FbCBQYXJkbywgMjgwNTAgTWFkcmlkLCBFc3Bhw7FhIiwicCI6IjkxMCAxNiA1MyAwNSIsInIiOjQuNiwiYyI6MjQwLCJoIjoiL2FwaS9mb3RvP3BsYWNlPUNoSUpmU25IRy1BclFnMFJiQlRyWFAtbGUzMCZpPTQiLCJvIjpbIjEwOjAw4oCTMjA6MDAiLCIxMDowMOKAkzIwOjAwIiwiMTA6MDDigJMyMDowMCIsIjEwOjAw4oCTMjA6MDAiLCIxMDowMOKAkzIwOjAwIiwiMTA6MDDigJMxNDowMCIsIkNlcnJhZG8iXSwiZiI6MTAsImciOlsiNiIsIjMiLCIyIiwiNyJdfQ",
  },
  {
    parada: 7,
    bloque: "M1",
    hora: "12:25",
    nombre: "3K Peluqueros",
    tipo: "Peluquería",
    path: "/s/3k-peluqueros?d=eyJuIjoiM0sgUGVsdXF1ZXJvcyIsInQiOiJQZWx1cXVlcsOtYSIsImQiOiJDLiBkZSBsYSBTaWVycmEgZGUgQXRhcHVlcmNhLCA2LCBGdWVuY2FycmFsLUVsIFBhcmRvLCAyODA1MCBNYWRyaWQsIEVzcGHDsWEiLCJwIjoiOTE3IDUwIDcyIDY0IiwiciI6NC43LCJjIjoyMTMsImgiOiIvYXBpL2ZvdG8_cGxhY2U9Q2hJSmc4N1NyT1FyUWcwUi1ubVpDTzF1TVpzJmk9MSIsIm8iOlsiMTA6MDDigJMyMDowMCIsIjEwOjAw4oCTMjA6MDAiLCIxMDowMOKAkzIwOjAwIiwiQ2VycmFkbyIsIjEwOjAw4oCTMjA6MDAiLCI5OjAw4oCTMTM6MzAiLCJDZXJyYWRvIl0sImYiOjEwLCJnIjpbIjAiLCIyIiwiNCIsIjUiXX0",
  },
  {
    parada: 8,
    bloque: "M1",
    hora: "12:45",
    nombre: "Nails & Body. Peluquería-Estética-Solarium.",
    tipo: "Peluquería y estética",
    path: "/s/nails-body-peluqueria-estetica-solarium?d=eyJuIjoiTmFpbHMgJiBCb2R5LiBQZWx1cXVlcsOtYS1Fc3TDqXRpY2EtU29sYXJpdW0uIiwidCI6IlBlbHVxdWVyw61hIHkgZXN0w6l0aWNhIiwiZCI6IkMuIGRlIEF6b2ZyYSwgMzEsIEZ1ZW5jYXJyYWwtRWwgUGFyZG8sIDI4MDUwIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTQgMjcgNDggODEiLCJyIjo0LjYsImMiOjMzNCwiaCI6Ii9hcGkvZm90bz9wbGFjZT1DaElKOV9EU1V1TXJRZzBSV2ZVQTRSWDNiTmcmaT0yIiwibyI6WyI5OjMw4oCTMjI6MDAiLCI5OjMw4oCTMjI6MDAiLCI5OjMw4oCTMjI6MDAiLCI5OjMw4oCTMjI6MDAiLCI5OjMw4oCTMjI6MDAiLCIxMDowMOKAkzE5OjAwIiwiQ2VycmFkbyJdLCJmIjoxMCwiZyI6WyI0IiwiNSIsIjMiLCIxIl19",
  },
  {
    parada: 9,
    bloque: "M1",
    hora: "13:05",
    nombre: "Fórmula de Belleza",
    tipo: "Peluquería y estética",
    path: "/s/formula-de-belleza?d=eyJuIjoiRsOzcm11bGEgZGUgQmVsbGV6YSIsInQiOiJQZWx1cXVlcsOtYSB5IGVzdMOpdGljYSIsImQiOiJDLiBkZSBFc3RlbGxhLCAxNywgRnVlbmNhcnJhbC1FbCBQYXJkbywgMjgwNTAgTWFkcmlkLCBFc3Bhw7FhIiwicCI6IjYzNSAxMSA2NiAwOCIsInIiOjQuNiwiYyI6MzEsImgiOiIvYXBpL2ZvdG8_cGxhY2U9Q2hJSjlXeE02Q0FyUWcwUnRnQm5uQTNCWmdRJmk9MiIsIm8iOlsiMTA6MDDigJMyMDowMCIsIjEwOjAw4oCTMjA6MDAiLCIxMDowMOKAkzIwOjAwIiwiMTA6MDDigJMyMDowMCIsIjEwOjAw4oCTMjA6MDAiLCIxMDowMOKAkzE0OjAwIiwiQ2VycmFkbyJdLCJmIjoxMCwiZyI6WyIwIiwiMSIsIjUiLCI0Il19",
  },
  {
    parada: 10,
    bloque: "M1",
    hora: "13:20",
    nombre: "Melanie Secretos del Agua Peluquería Saludable",
    tipo: "Peluquería",
    path: "/s/melanie-secretos-del-agua-peluqueria-saludable?d=eyJuIjoiTWVsYW5pZSBTZWNyZXRvcyBkZWwgQWd1YSBQZWx1cXVlcsOtYSBTYWx1ZGFibGUiLCJ0IjoiUGVsdXF1ZXLDrWEiLCJkIjoiQXYuIGRlbCBDYW1pbm8gZGUgU2FudGlhZ28sIDksIEZ1ZW5jYXJyYWwtRWwgUGFyZG8sIDI4MDUwIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTkgMzUgMDIgOTQiLCJyIjo0LjksImMiOjEzNywiaCI6Ii9hcGkvZm90bz9wbGFjZT1DaElKQjItM3A0SXJRZzBSdWJaZ3IxSFlGS1UmaT0xIiwibyI6WyJDZXJyYWRvIiwiMTE6MDDigJMyMDowMCIsIjExOjAw4oCTMjA6MDAiLCIxMTowMOKAkzIwOjAwIiwiMTE6MDDigJMyMDowMCIsIjk6MzDigJMxNTowMCIsIkNlcnJhZG8iXSwiZiI6MTAsImciOlsiMiIsIjUiLCIzIiwiMCJdfQ",
  },
  {
    parada: 11,
    bloque: "M2",
    hora: "15:00",
    nombre: "Cleopatra",
    tipo: "Peluquería",
    path: "/s/cleopatra?d=eyJuIjoiQ2xlb3BhdHJhIiwidCI6IlBlbHVxdWVyw61hIiwiZCI6IkMuIGRlIGxhIFByaW5jZXNhIGRlIMOJYm9saSwgOUosIEhvcnRhbGV6YSwgMjgwNTAgTWFkcmlkLCBFc3Bhw7FhIiwicCI6IjkxNCAzOCA0OSAxMCIsInIiOjQuOCwiYyI6MTIwLCJoIjoiL2FwaS9mb3RvP3BsYWNlPUNoSUptM21YUDY0dVFnMFJlYWVHaXJnLUdTTSZpPTAiLCJvIjpbIjEwOjAw4oCTMTQ6MDAsIDE1OjAw4oCTMjA6MDAiLCIxMDowMOKAkzE0OjAwLCAxNTowMOKAkzIwOjAwIiwiMTA6MDDigJMxNDowMCwgMTU6MDDigJMyMDowMCIsIjEwOjAw4oCTMTQ6MDAsIDE1OjAw4oCTMjA6MDAiLCIxMDowMOKAkzE0OjAwLCAxNTowMOKAkzIwOjAwIiwiMTA6MDDigJMxNDowMCIsIkNlcnJhZG8iXSwiZiI6MTAsImciOlsiMiIsIjUiLCIzIiwiMSJdfQ",
  },
  {
    parada: 12,
    bloque: "M2",
    hora: "15:20",
    nombre: "Bio Roma",
    tipo: "Peluquería",
    path: "/s/bio-roma?d=eyJuIjoiQmlvIFJvbWEiLCJ0IjoiUGVsdXF1ZXLDrWEiLCJkIjoiQy4gZGVsIFByw61uY2lwZSBDYXJsb3MsIDE3LCBIb3J0YWxlemEsIDI4MDUwIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTcgNTAgMDkgOTciLCJyIjo0LjQsImMiOjYwMiwiaCI6Ii9hcGkvZm90bz9wbGFjZT1DaElKb1hTN29La3VRZzBSTjcyWXlGVzVmb2cmaT0xIiwibyI6WyIxMDowMOKAkzIwOjMwIiwiMTA6MDDigJMyMDozMCIsIjEwOjAw4oCTMjA6MzAiLCIxMDowMOKAkzIwOjMwIiwiMTA6MDDigJMyMDozMCIsIjEwOjAw4oCTMjE6MDAiLCJDZXJyYWRvIl0sImYiOjEwLCJnIjpbIjAiLCI0IiwiMyIsIjUiXX0",
  },
  {
    parada: 13,
    bloque: "M2",
    hora: "15:45",
    nombre: "PeluChic",
    tipo: "Peluquería",
    path: "/s/peluchic?d=eyJuIjoiUGVsdUNoaWMiLCJ0IjoiUGVsdXF1ZXLDrWEiLCJkIjoiQ2FsbGUgUHJpbmNlc2EgZGUgRWJvbGksIDEwMCwgRXNxdWluYSBjb24sIEMuIGRlIE1hcsOtYSBUdWRvciwgMTQsIExvYyAxMDQsIEhvcnRhbGV6YSwgMjgwNTAgTWFkcmlkLCBFc3Bhw7FhIiwicCI6IjY2NiA3NyA2NyAzMSIsInIiOjQuNSwiYyI6ODEsImgiOiIvYXBpL2ZvdG8_cGxhY2U9Q2hJSmNfZFkzcTB1UWcwUmVlQXpjMVkzaXJzJmk9MCIsIm8iOlsiQ2VycmFkbyIsIjEwOjAw4oCTMjA6MDAiLCIxMDowMOKAkzIwOjAwIiwiMTA6MDDigJMyMDowMCIsIjEwOjAw4oCTMjA6MDAiLCI5OjAw4oCTMTQ6MDAiLCJDZXJyYWRvIl0sImYiOjEwLCJnIjpbIjMiLCI0IiwiMiIsIjUiXX0",
  },
  {
    parada: 14,
    bloque: "M2",
    hora: "16:15",
    nombre: "Peluquería SOMO",
    tipo: "Peluquería",
    path: "/s/peluqueria-somo?d=eyJuIjoiUGVsdXF1ZXLDrWEgU09NTyIsInQiOiJQZWx1cXVlcsOtYSIsImQiOiJDLiBkZSBNYW51ZWwgUG9tYm8gQW5ndWxvLCA4LCBIb3J0YWxlemEsIDI4MDUwIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTMgOTIgMzggNzgiLCJyIjo0LjQsImMiOjQ0LCJoIjoiL2FwaS9mb3RvP3BsYWNlPUNoSUpsM2tsV0E4c1FnMFJKelZBWVpoTXNrVSZpPTEiLCJvIjpbIjEwOjAw4oCTMTQ6MDAsIDE2OjAw4oCTMjA6MDAiLCIxMDowMOKAkzE0OjAwLCAxNjowMOKAkzIwOjAwIiwiMTA6MDDigJMxNDowMCwgMTY6MDDigJMyMDowMCIsIjEwOjAw4oCTMTQ6MDAsIDE2OjAw4oCTMjA6MDAiLCIxMDowMOKAkzE0OjAwLCAxNjowMOKAkzIwOjAwIiwiMTA6MDDigJMxNDowMCIsIkNlcnJhZG8iXSwiZiI6NCwiZyI6WyIwIiwiMiIsIjMiXX0",
  },
  {
    parada: 15,
    bloque: "M2",
    hora: "16:30",
    nombre: "DE TOMÁS barberia peluqueria de caballeros",
    tipo: "Barbería",
    path: "/s/de-tomas-barberia-peluqueria-de-caballeros?d=eyJuIjoiREUgVE9Nw4FTIGJhcmJlcmlhIHBlbHVxdWVyaWEgZGUgY2FiYWxsZXJvcyIsInQiOiJCYXJiZXLDrWEiLCJkIjoiQy4gZGUgTWFudWVsIFBvbWJvIEFuZ3VsbywgOCwgSG9ydGFsZXphLCAyODA1MCBNYWRyaWQsIEVzcGHDsWEiLCJwIjoiOTE5IDIxIDQyIDE4IiwiciI6NC45LCJjIjoxNTEsImgiOiIvYXBpL2ZvdG8_cGxhY2U9Q2hJSlUxd0tXaUF0UWcwUnRlZUxqeVRpRHJVJmk9MiIsIm8iOlsiMTA6MDDigJMxNDozMCwgMTY6MDDigJMyMDozMCIsIjEwOjAw4oCTMTQ6MzAsIDE2OjAw4oCTMjA6MzAiLCIxMDowMOKAkzE0OjMwLCAxNjowMOKAkzIwOjMwIiwiMTA6MDDigJMxNDozMCwgMTY6MDDigJMyMDozMCIsIjEwOjAw4oCTMTQ6MzAsIDE1OjMw4oCTMjA6MzAiLCJDZXJyYWRvIiwiQ2VycmFkbyJdLCJmIjoxMCwiZyI6WyI1IiwiNiIsIjEiLCI0Il19",
  },
  {
    parada: 16,
    bloque: "X1",
    hora: "14:10",
    nombre: "Aire Nuevo Peluquería",
    tipo: "Peluquería",
    path: "/s/aire-nuevo-peluqueria?d=eyJuIjoiQWlyZSBOdWV2byBQZWx1cXVlcsOtYSIsInQiOiJQZWx1cXVlcsOtYSIsImQiOiJDLiBkZSBPw7FhLCAxMywgSG9ydGFsZXphLCAyODA1MCBNYWRyaWQsIEVzcGHDsWEiLCJwIjoiOTEzIDAyIDk2IDQyIiwiciI6NC43LCJjIjo0NywiaCI6Ii9hcGkvZm90bz9wbGFjZT1DaElKUzA3RFhWRXBRZzBSVVhsa2RSU21mRVEmaT04IiwibyI6WyIxMDowMOKAkzE4OjMwIiwiMTA6MDDigJMxODozMCIsIjEwOjAw4oCTMTg6MzAiLCIxMDowMOKAkzE4OjMwIiwiMTA6MDDigJMxODozMCIsIjEwOjAw4oCTMTM6MzAiLCJDZXJyYWRvIl0sImYiOjEwLCJnIjpbIjEiLCI1IiwiMiIsIjMiXX0",
  },
  {
    parada: 17,
    bloque: "X1",
    hora: "14:35",
    nombre: "Kana'sh Peluqueros",
    tipo: "Peluquería",
    path: "/s/kana-sh-peluqueros?d=eyJuIjoiS2FuYSdzaCBQZWx1cXVlcm9zIiwidCI6IlBlbHVxdWVyw61hIiwiZCI6IkMuIGRlIE_DsWEsIDk1LCBVcmIsIEhvcnRhbGV6YSwgMjgwNTAgTWFkcmlkLCBFc3Bhw7FhIiwicCI6IjkxMyAwMiA5MyA4MSIsInIiOjQuNywiYyI6OTgsImgiOiIvYXBpL2ZvdG8_cGxhY2U9Q2hJSkJVVlVPRk1wUWcwUkFfWl8yX3ZpLXY4Jmk9MSIsIm8iOlsiOTozMOKAkzIwOjAwIiwiOTozMOKAkzIwOjAwIiwiOTozMOKAkzIwOjAwIiwiOTozMOKAkzIwOjAwIiwiOTozMOKAkzIwOjAwIiwiOTozMOKAkzE0OjAwIiwiQ2VycmFkbyJdLCJmIjoxMCwiZyI6WyIyIiwiMyIsIjUiLCI0Il19",
  },
  {
    parada: 18,
    bloque: "X1",
    hora: "14:55",
    nombre: "ARTE PELUQUEROS",
    tipo: "Peluquería",
    path: "/s/arte-peluqueros?d=eyJuIjoiQVJURSBQRUxVUVVFUk9TIiwidCI6IlBlbHVxdWVyw61hIiwiZCI6IkMuIGRlIE_DsWEsIDg5LCBIb3J0YWxlemEsIDI4MDUwIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTcgNjYgNjMgODQiLCJyIjo0LjcsImMiOjE4NywiaCI6Ii9hcGkvZm90bz9wbGFjZT1DaElKV3g2S0sxTXBRZzBSWW9XNm5ya3pfdk0maT0zIiwibyI6WyIxMDowMOKAkzE0OjMwIiwiMTA6MDDigJMxOTowMCIsIjEwOjAw4oCTMTk6MDAiLCIxMDowMOKAkzE5OjAwIiwiMTA6MDDigJMxOTowMCIsIkNlcnJhZG8iLCJDZXJyYWRvIl0sImYiOjEwLCJnIjpbIjciLCI5IiwiMSIsIjUiXX0",
  },
  {
    parada: 19,
    bloque: "X1",
    hora: "15:15",
    nombre: "La Bigotería",
    tipo: "Barbería",
    path: "/s/la-bigoteria?d=eyJuIjoiTGEgQmlnb3RlcsOtYSIsInQiOiJCYXJiZXLDrWEiLCJkIjoiQy4gZGUgT8OxYSwgMTcxLCBIb3J0YWxlemEsIDI4MDUwIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTEgMjggMTEgMDMiLCJyIjo0LjcsImMiOjM0MiwiaCI6Ii9hcGkvZm90bz9wbGFjZT1DaElKRXlJVDRxd3VRZzBSRU12U19tZFdNcEEmaT0wIiwibyI6WyIxMDowMOKAkzIxOjAwIiwiMTA6MDDigJMyMTowMCIsIjEwOjAw4oCTMjE6MDAiLCIxMDowMOKAkzIxOjAwIiwiMTA6MDDigJMyMTowMCIsIjEwOjAw4oCTMTQ6MDAiLCJDZXJyYWRvIl0sImYiOjEwLCJnIjpbIjIiLCI1IiwiMSIsIjMiXX0",
  },
  {
    parada: 20,
    bloque: "X2",
    hora: "14:10",
    nombre: "Silvia García Nails-Hair-Beauty",
    tipo: "Peluquería y estética",
    path: "/s/silvia-garcia-nails-hair-beauty?d=eyJuIjoiU2lsdmlhIEdhcmPDrWEgTmFpbHMtSGFpci1CZWF1dHkiLCJ0IjoiUGVsdXF1ZXLDrWEgeSBlc3TDqXRpY2EiLCJkIjoiQXYuIGRlIEpvc8OpIEFudG9uaW8gQ29ycmFsZXMsIDEsIEhvcnRhbGV6YSwgMjgwNTUgTWFkcmlkLCBFc3Bhw7FhIiwicCI6IjY0OCAxNyA3OSA1MyIsInIiOjQuNywiYyI6OTgsImgiOiIvYXBpL2ZvdG8_cGxhY2U9Q2hJSnVlMmtVVXd2UWcwUllUN0RBQVh0UllzJmk9MCIsIm8iOlsiMTA6MDDigJMyMDowMCIsIjEwOjAw4oCTMjA6MDAiLCIxMDowMOKAkzIwOjAwIiwiMTA6MDDigJMyMDowMCIsIjEwOjAw4oCTMjA6MDAiLCIxMDowMOKAkzE0OjAwIiwiQ2VycmFkbyJdLCJmIjoxMCwiZyI6WyIzIiwiNCIsIjEiLCIyIl19",
  },
  {
    parada: 21,
    bloque: "X2",
    hora: "14:40",
    nombre: "Yolanda Molina Peluqueros y Estilistas",
    tipo: "Peluquería",
    path: "/s/yolanda-molina-peluqueros-y-estilistas?d=eyJuIjoiWW9sYW5kYSBNb2xpbmEgUGVsdXF1ZXJvcyB5IEVzdGlsaXN0YXMiLCJ0IjoiUGVsdXF1ZXLDrWEiLCJkIjoiQXYuIGRlIE1hbnVlbCBGcmFnYSBJcmliYXJuZSwgMjQsIEhvcnRhbGV6YSwgMjgwNTUgTWFkcmlkLCBFc3Bhw7FhIiwicCI6IjkxMCA1MiA3MiAyNCIsInIiOjQuNywiYyI6MzA1LCJoIjoiL2FwaS9mb3RvP3BsYWNlPUNoSUp0WEE3eUhFdVFnMFJYbnJlT0hWdWFJZyZpPTEiLCJvIjpbIjEwOjAw4oCTMjA6MDAiLCIxMDowMOKAkzIwOjAwIiwiMTA6MDDigJMyMDowMCIsIjEwOjAw4oCTMjA6MDAiLCIxMDowMOKAkzIwOjAwIiwiOTowMOKAkzE0OjAwIiwiQ2VycmFkbyJdLCJmIjoxMCwiZyI6WyIyIiwiMyIsIjUiLCI2Il19",
  },
  {
    parada: 22,
    bloque: "X2",
    hora: "15:20",
    nombre: "6TREINTA Barbershop",
    tipo: "Barbería",
    path: "/s/6treinta-barbershop?d=eyJuIjoiNlRSRUlOVEEgQmFyYmVyc2hvcCIsInQiOiJCYXJiZXLDrWEiLCJkIjoiQXYuIGRlIE1hbnVlbCBGcmFnYSBJcmliYXJuZSwgOTAsIExvYyA0LCBIb3J0YWxlemEsIDI4MDU1IE1hZHJpZCwgRXNwYcOxYSIsInAiOiI2MTQgMDUgNzggNDQiLCJyIjo1LCJjIjoyMjcsImgiOiIvYXBpL2ZvdG8_cGxhY2U9Q2hJSnpYM1VHRDR2UWcwUnBEakRMdlB5amlvJmk9NCIsIm8iOlsiMTA6MDDigJMyMTowMCIsIjEwOjAw4oCTMjE6MDAiLCIxMDowMOKAkzIxOjAwIiwiMTA6MDDigJMyMTowMCIsIjEwOjAw4oCTMjE6MDAiLCI5OjAw4oCTMTU6MDAiLCJDZXJyYWRvIl0sImYiOjEwLCJnIjpbIjAiLCI1IiwiMiIsIjEiXX0",
  },
  {
    parada: 23,
    bloque: "X2",
    hora: "16:05",
    nombre: "THE BEST SHAVE & BARBER",
    tipo: "Barbería",
    path: "/s/the-best-shave-barber?d=eyJuIjoiVEhFIEJFU1QgU0hBVkUgJiBCQVJCRVIiLCJ0IjoiQmFyYmVyw61hIiwiZCI6IkNhbGxlIHJhZmFlbGEgYXBhcmljaW8sIEF2LiBkZSBNYXJ1amEgTWFsbG8sIEhvcnRhbGV6YSwgMjgwNTUgTWFkcmlkLCBFc3Bhw7FhIiwicCI6IjYyMiA4NyA0NiAzOCIsInIiOjQuOCwiYyI6MTMyLCJoIjoiL2FwaS9mb3RvP3BsYWNlPUNoSUpKV1NSSl9vdlFnMFJJdDRFNUM2MU1kZyZpPTAiLCJvIjpbIjEwOjAw4oCTMTQ6MDAsIDE2OjAw4oCTMjA6MzAiLCIxMDowMOKAkzE0OjAwLCAxNjowMOKAkzIwOjMwIiwiMTA6MDDigJMxNDowMCwgMTY6MDDigJMyMDozMCIsIjEwOjAw4oCTMTQ6MDAsIDE2OjAw4oCTMjA6MzAiLCIxMDowMOKAkzE0OjAwLCAxNjowMOKAkzIwOjMwIiwiMTA6MDDigJMxNDowMCwgMTY6MDDigJMyMDozMCIsIkNlcnJhZG8iXSwiZiI6MTAsImciOlsiNCIsIjIiLCI1IiwiMyJdfQ",
  },
  {
    parada: 24,
    bloque: "J1",
    hora: "10:00",
    nombre: "Barberia Soria",
    tipo: "Barbería",
    path: "/s/barberia-soria?d=eyJuIjoiQmFyYmVyaWEgU29yaWEiLCJ0IjoiQmFyYmVyw61hIiwiZCI6IkMuIGRlIFBlZ2FzbywgMTIsIEhvcnRhbGV6YSwgMjgwNDMgTWFkcmlkLCBFc3Bhw7FhIiwicCI6IjkxMSA0NyAzOCA2NiIsInIiOjQuNywiYyI6MjE0LCJoIjoiL2FwaS9mb3RvP3BsYWNlPUNoSUpseEt4RjlzdVFnMFJ5cC1xd3haelhUQSZpPTIiLCJvIjpbIjEwOjAw4oCTMjA6MDAiLCIxMDowMOKAkzIwOjAwIiwiMTA6MDDigJMyMDowMCIsIjEwOjAw4oCTMjA6MDAiLCIxMDowMOKAkzIwOjAwIiwiMTA6MDDigJMxNTowMCIsIkNlcnJhZG8iXSwiZiI6MTAsImciOlsiMSIsIjciLCI5Il19",
  },
  {
    parada: 25,
    bloque: "J1",
    hora: "10:25",
    nombre: "Peluquería César",
    tipo: "Peluquería",
    path: "/s/peluqueria-cesar?d=eyJuIjoiUGVsdXF1ZXLDrWEgQ8Opc2FyIiwidCI6IlBlbHVxdWVyw61hIiwiZCI6IkNhcnIuIGRlIENhbmlsbGFzLCA0MSwgSG9ydGFsZXphLCAyODA0MyBNYWRyaWQsIEVzcGHDsWEiLCJwIjoiOTE3IDU5IDQ2IDA3IiwiciI6NC42LCJjIjoxMzIsImgiOiIvYXBpL2ZvdG8_cGxhY2U9Q2hJSkQxckVlOXN1UWcwUmZqc183SnY3M05nJmk9OSIsIm8iOlsiMTA6MDDigJMyMDozMCIsIjEwOjAw4oCTMjA6MzAiLCIxMDowMOKAkzIwOjMwIiwiMTA6MDDigJMyMDozMCIsIjEwOjAw4oCTMjA6MzAiLCIxMDowMOKAkzE0OjMwIiwiQ2VycmFkbyJdLCJmIjoxMCwiZyI6WyI3IiwiOCIsIjMiLCIyIl19",
  },
  {
    parada: 26,
    bloque: "J1",
    hora: "10:50",
    nombre: "Peluquería Reduan",
    tipo: "Peluquería",
    path: "/s/peluqueria-reduan?d=eyJuIjoiUGVsdXF1ZXLDrWEgUmVkdWFuIiwidCI6IlBlbHVxdWVyw61hIiwiZCI6IkMuIGRlIEzDs3BleiBkZSBIb3lvcywgNDU0LCBIb3J0YWxlemEsIDI4MDQzIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI2NzIgNDEgNTcgNjYiLCJyIjo0LjcsImMiOjc4LCJvIjpbIjEwOjMw4oCTMTQ6MDAsIDE3OjAw4oCTMjA6MzAiLCIxMDozMOKAkzE0OjAwLCAxNzowMOKAkzIwOjMwIiwiMTA6MzDigJMxNDowMCwgMTc6MDDigJMyMDozMCIsIjEwOjMw4oCTMTQ6MDAsIDE3OjAw4oCTMjA6MzAiLCIxMDozMOKAkzE0OjAwLCAxNzowMOKAkzIwOjMwIiwiMTA6MzDigJMxNjowMCIsIkNlcnJhZG8iXX0",
  },
  {
    parada: 27,
    bloque: "J1",
    hora: "11:10",
    nombre: "Peluquería Barbería de caballeros Rafael",
    tipo: "Barbería",
    path: "/s/peluqueria-barberia-de-caballeros-rafael?d=eyJuIjoiUGVsdXF1ZXLDrWEgQmFyYmVyw61hIGRlIGNhYmFsbGVyb3MgUmFmYWVsIiwidCI6IkJhcmJlcsOtYSIsImQiOiJDLiBkZSBMw7NwZXogZGUgSG95b3MsIDM2MSwgSG9ydGFsZXphLCAyODAzMyBNYWRyaWQsIEVzcGHDsWEiLCJwIjoiNjYxIDg4IDc2IDY0IiwiciI6NC43LCJjIjoxODUsImgiOiIvYXBpL2ZvdG8_cGxhY2U9Q2hJSmhibnRfTVV1UWcwUmIyekg0dEtQbkdFJmk9MSIsIm8iOlsiOTozMOKAkzE0OjAwLCAxNjozMOKAkzIxOjAwIiwiOTozMOKAkzE0OjAwLCAxNjozMOKAkzIxOjAwIiwiOTozMOKAkzE0OjAwLCAxNjozMOKAkzIxOjAwIiwiOTozMOKAkzE0OjAwLCAxNjozMOKAkzIxOjAwIiwiOTozMOKAkzE0OjAwLCAxNjozMOKAkzIxOjAwIiwiOTozMOKAkzE0OjAwLCAxNjozMOKAkzIxOjAwIiwiMTA6MzDigJMxNDowMCJdLCJmIjoxMCwiZyI6WyIwIiwiNSIsIjIiLCIzIl19",
  },
  {
    parada: 28,
    bloque: "J1",
    hora: "11:30",
    nombre: "Peluqueria Caballeros Jesús Moreno",
    tipo: "Barbería",
    path: "/s/peluqueria-caballeros-jesus-moreno?d=eyJuIjoiUGVsdXF1ZXJpYSBDYWJhbGxlcm9zIEplc8O6cyBNb3Jlbm8iLCJ0IjoiQmFyYmVyw61hIiwiZCI6IkMuIEJpb3NjYSwgNiwgSG9ydGFsZXphLCAyODA0MyBNYWRyaWQsIEVzcGHDsWEiLCJwIjoiOTE3IDYzIDgyIDU4IiwiciI6NC45LCJjIjoxMjEsImgiOiIvYXBpL2ZvdG8_cGxhY2U9Q2hJSnBUUmpLc1F1UWcwUkV1T0NMT1dybDFnJmk9MyIsIm8iOlsiOTozMOKAkzE0OjAwLCAxNjozMOKAkzIwOjMwIiwiOTozMOKAkzE0OjAwLCAxNjozMOKAkzIwOjMwIiwiOTozMOKAkzE0OjAwLCAxNjozMOKAkzIwOjMwIiwiOTozMOKAkzE0OjAwLCAxNjozMOKAkzIwOjMwIiwiOTozMOKAkzE0OjAwLCAxNjozMOKAkzIwOjMwIiwiOTozMOKAkzE0OjAwIiwiQ2VycmFkbyJdLCJmIjoxMCwiZyI6WyI1IiwiNiIsIjkiLCIyIl19",
  },
  {
    parada: 29,
    bloque: "J1",
    hora: "11:45",
    nombre: "Bárbara del Amor López, Peluqueria",
    tipo: "Peluquería",
    path: "/s/barbara-del-amor-lopez-peluqueria?d=eyJuIjoiQsOhcmJhcmEgZGVsIEFtb3IgTMOzcGV6LCBQZWx1cXVlcmlhIiwidCI6IlBlbHVxdWVyw61hIiwiZCI6IkMuIEJpb3NjYSwgMzEsIEhvcnRhbGV6YSwgMjgwNDMgTWFkcmlkLCBFc3Bhw7FhIiwicCI6IjY3MCA4NiA5OSA4OSIsInIiOjQuOCwiYyI6MjYsIm8iOlsiMTA6MDDigJMxOTowMCIsIjEwOjAw4oCTMTk6MDAiLCIxMDowMOKAkzE5OjAwIiwiMTA6MDDigJMxOTowMCIsIjEwOjAw4oCTMTk6MDAiLCI5OjAw4oCTMTQ6MDAiLCJDZXJyYWRvIl19",
  },
  {
    parada: 30,
    bloque: "J1",
    hora: "12:05",
    nombre: "Valentino Roma Estilistas",
    tipo: "Peluquería",
    path: "/s/valentino-roma-estilistas?d=eyJuIjoiVmFsZW50aW5vIFJvbWEgRXN0aWxpc3RhcyIsInQiOiJQZWx1cXVlcsOtYSIsImQiOiJDLiBkZSBMw7NwZXogZGUgSG95b3MsIDM3NSwgUG9zdGVyaW9yIExvY2FsLCBIb3J0YWxlemEsIDI4MDQzIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI2NzIgMzUgMjYgNzAiLCJyIjo0LjksImMiOjE1NSwiaCI6Ii9hcGkvZm90bz9wbGFjZT1DaElKdVRrTHBzZ3VRZzBSLWR0RXJOekFQcnMmaT0wIiwibyI6WyIxMDowMOKAkzE1OjAwIiwiMTA6MDDigJMxOTowMCIsIjEwOjAw4oCTMTk6MDAiLCIxMDowMOKAkzE5OjAwIiwiMTA6MDDigJMxOTowMCIsIjk6MDDigJMxNTowMCIsIkNlcnJhZG8iXSwiZiI6MTAsImciOlsiMSIsIjQiLCIyIiwiNSJdfQ",
  },
  {
    parada: 31,
    bloque: "J1",
    hora: "12:25",
    nombre: "Peluquería Rizus",
    tipo: "Peluquería",
    path: "/s/peluqueria-rizus?d=eyJuIjoiUGVsdXF1ZXLDrWEgUml6dXMiLCJ0IjoiUGVsdXF1ZXLDrWEiLCJkIjoiQy4gZGUgQ2FsYXNwYXJyYSwgMjEsIEhvcnRhbGV6YSwgMjgwMzMgTWFkcmlkLCBFc3Bhw7FhIiwicCI6IjkxMyA4MSA4NiAzNSIsInIiOjQuOSwiYyI6MjI3LCJoIjoiL2FwaS9mb3RvP3BsYWNlPUNoSUp2WmRNQXNrdVFnMFJhbjQ3YU1URGlfQSZpPTUiLCJvIjpbIjk6MzDigJMxOTowMCIsIjk6MzDigJMxOTowMCIsIjk6MzDigJMxOTowMCIsIjk6MzDigJMxOTowMCIsIjk6MzDigJMxOTowMCIsIjk6MDDigJMxNDowMCIsIkNlcnJhZG8iXSwiZiI6MTAsImciOlsiMiIsIjgiLCIwIiwiNCJdfQ",
  },
  {
    parada: 32,
    bloque: "J1",
    hora: "12:40",
    nombre: "Peluquería Blanco",
    tipo: "Peluquería",
    path: "/s/peluqueria-blanco?d=eyJuIjoiUGVsdXF1ZXLDrWEgQmxhbmNvIiwidCI6IlBlbHVxdWVyw61hIiwiZCI6IkMuIGRlIENhbGFzcGFycmEsIDIzLCBIb3J0YWxlemEsIDI4MDMzIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTMgODEgNzYgNzYiLCJyIjo0LjgsImMiOjIyMiwiaCI6Ii9hcGkvZm90bz9wbGFjZT1DaElKdFl2b19jZ3VRZzBSNEowNFlhUkY4dTQmaT02IiwibyI6WyI5OjE14oCTMTQ6MDAsIDE2OjAw4oCTMjA6MDAiLCI5OjE14oCTMTQ6MDAsIDE2OjAw4oCTMjA6MDAiLCI5OjE14oCTMTQ6MDAsIDE2OjAw4oCTMjA6MDAiLCI5OjE14oCTMTQ6MDAsIDE2OjAw4oCTMjA6MDAiLCI5OjE14oCTMTQ6MDAsIDE2OjAw4oCTMjA6MDAiLCI5OjAw4oCTMTQ6MDAiLCJDZXJyYWRvIl0sImYiOjEwLCJnIjpbIjAiLCI1IiwiOSIsIjMiXX0",
  },
  {
    parada: 33,
    bloque: "J1",
    hora: "13:00",
    nombre: "El Jefe BarberShop",
    tipo: "Barbería",
    path: "/s/el-jefe-barbershop?d=eyJuIjoiRWwgSmVmZSBCYXJiZXJTaG9wIiwidCI6IkJhcmJlcsOtYSIsImQiOiJDLiBkZSBsYSBDb3N0YSBkZWwgU29sLCA5LCBIb3J0YWxlemEsIDI4MDMzIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTAgMjYgNjggNTkiLCJyIjo0LjksImMiOjI0MiwiaCI6Ii9hcGkvZm90bz9wbGFjZT1DaElKVTQ1TmZNZ3VRZzBSWTczbXNnbGpMVG8maT0xIiwibyI6WyIxMDowMOKAkzIwOjMwIiwiMTA6MDDigJMyMDozMCIsIjEwOjAw4oCTMjA6MzAiLCIxMDowMOKAkzIwOjMwIiwiMTA6MDDigJMyMTowMCIsIjEwOjAw4oCTMjE6MDAiLCIxMTowMOKAkzE2OjAwIl0sImYiOjEwLCJnIjpbIjIiLCI1IiwiMyIsIjAiXX0",
  },
  {
    parada: 34,
    bloque: "J1",
    hora: "13:20",
    nombre: "Peluquería Caballeros Alicia",
    tipo: "Barbería",
    path: "/s/peluqueria-caballeros-alicia?d=eyJuIjoiUGVsdXF1ZXLDrWEgQ2FiYWxsZXJvcyBBbGljaWEiLCJ0IjoiQmFyYmVyw61hIiwiZCI6IkF2LiBkZSBsYSBWaXJnZW4gZGVsIENhcm1lbiwgMzksIEhvcnRhbGV6YSwgMjgwMzMgTWFkcmlkLCBFc3Bhw7FhIiwicCI6IjY0OCA2MiAxMSA1MiIsInIiOjQuOCwiYyI6NDEsImgiOiIvYXBpL2ZvdG8_cGxhY2U9Q2hJSlUtYzloTWN1UWcwUjFONFdtQU9OX2trJmk9MCIsIm8iOlsiOTozMOKAkzE0OjAwLCAxNjozMOKAkzIwOjAwIiwiOTozMOKAkzE0OjAwLCAxNjozMOKAkzIwOjAwIiwiOTozMOKAkzE0OjAwLCAxNjozMOKAkzIwOjAwIiwiOTozMOKAkzE0OjAwLCAxNjozMOKAkzIwOjAwIiwiOTozMOKAkzE0OjAwLCAxNjozMOKAkzIwOjAwIiwiQ2VycmFkbyIsIkNlcnJhZG8iXSwiZiI6MiwiZyI6WyIxIl19",
  },
  {
    parada: 35,
    bloque: "J1",
    hora: "13:40",
    nombre: "Peluquería Cristina",
    tipo: "Peluquería",
    path: "/s/peluqueria-cristina?d=eyJuIjoiUGVsdXF1ZXLDrWEgQ3Jpc3RpbmEiLCJ0IjoiUGVsdXF1ZXLDrWEiLCJkIjoiQy4gZGUgU3RhLiBBZGVsYSwgMTMsIEhvcnRhbGV6YSwgMjgwMzMgTWFkcmlkLCBFc3Bhw7FhIiwicCI6IjkxMyA4MSA1MyAwNyIsInIiOjQuOCwiYyI6NjksImgiOiIvYXBpL2ZvdG8_cGxhY2U9Q2hJSkI1NjRCTGt1UWcwUkxBQVY5SzdYcExzJmk9NSIsIm8iOlsiMTA6MDDigJMxOTowMCIsIjEwOjAw4oCTMTk6MDAiLCIxMDowMOKAkzE5OjAwIiwiMTA6MDDigJMxOTowMCIsIjEwOjAw4oCTMTk6MDAiLCIxMDowMOKAkzE0OjAwIiwiQ2VycmFkbyJdLCJmIjo4LCJnIjpbIjEiLCI2IiwiMiJdfQ",
  },
  {
    parada: 36,
    bloque: "J2",
    hora: "15:00",
    nombre: "Peluqueria Vanessa Cid",
    tipo: "Peluquería",
    path: "/s/peluqueria-vanessa-cid?d=eyJuIjoiUGVsdXF1ZXJpYSBWYW5lc3NhIENpZCIsInQiOiJQZWx1cXVlcsOtYSIsImQiOiJkZSwgQy4gZGUgbG9zIEFyY29zLCAzLCBIb3J0YWxlemEsIDI4MDMzIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTcgNjQgMTQgODQiLCJyIjo0LjcsImMiOjMwLCJoIjoiL2FwaS9mb3RvP3BsYWNlPUNoSUpWMnB2QTc4dVFnMFJlY2g5MEVpTnFLdyZpPTMiLCJvIjpbIjEwOjAw4oCTMTg6MDAiLCIxMDowMOKAkzE4OjAwIiwiMTA6MDDigJMxODowMCIsIjEwOjAw4oCTMTg6MDAiLCIxMDowMOKAkzE4OjAwIiwiMTA6MDDigJMxMzowMCIsIkNlcnJhZG8iXSwiZiI6MTAsImciOlsiMiIsIjEiLCI1IiwiMCJdfQ",
  },
  {
    parada: 37,
    bloque: "J2",
    hora: "15:20",
    nombre: "Peluqueria Sara Valledor",
    tipo: "Peluquería",
    path: "/s/peluqueria-sara-valledor?d=eyJuIjoiUGVsdXF1ZXJpYSBTYXJhIFZhbGxlZG9yIiwidCI6IlBlbHVxdWVyw61hIiwiZCI6IkMuIGRlIFN0YS4gU3VzYW5hLCAzLCBIb3J0YWxlemEsIDI4MDMzIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTcgNjMgODEgNzciLCJyIjo0LjgsImMiOjczLCJoIjoiL2FwaS9mb3RvP3BsYWNlPUNoSUpMWndQVTc4dVFnMFJYYm5JdDdfVjFEcyZpPTIiLCJvIjpbIjEwOjAw4oCTMTU6MDAiLCIxMDowMOKAkzE5OjAwIiwiMTA6MDDigJMxOTowMCIsIjEwOjAw4oCTMTk6MDAiLCIxMDowMOKAkzE5OjAwIiwiMTA6MDDigJMxNDowMCIsIkNlcnJhZG8iXSwiZiI6MTAsImciOlsiMSIsIjQiLCI1IiwiMyJdfQ",
  },
  {
    parada: 38,
    bloque: "J2",
    hora: "15:40",
    nombre: "Yolanda Quesada Peluquería con Estética",
    tipo: "Peluquería y estética",
    path: "/s/yolanda-quesada-peluqueria-con-estetica?d=eyJuIjoiWW9sYW5kYSBRdWVzYWRhIFBlbHVxdWVyw61hIGNvbiBFc3TDqXRpY2EiLCJ0IjoiUGVsdXF1ZXLDrWEgeSBlc3TDqXRpY2EiLCJkIjoiQy4gQXJ6w7phLCA2IGVzcXVpbmEgQXphZ3JhIENhbGxlIEFyesO6YSwgQy4gQXphZ3JhLCA2IGVzcXVpbmEsIEhvcnRhbGV6YSwgMjgwMzMgTWFkcmlkLCBFc3Bhw7FhIiwicCI6IjY2NSAxMCA1NyAxMCIsInIiOjQuNiwiYyI6MTMsImgiOiIvYXBpL2ZvdG8_cGxhY2U9Q2hJSjBkRUJFQkF2UWcwUmVWRXQyNTlzN3FJJmk9MCIsIm8iOlsiMTA6MDDigJMxODozMCIsIjEwOjAw4oCTMTg6MzAiLCIxMDowMOKAkzE4OjMwIiwiMTA6MDDigJMxODozMCIsIjEwOjAw4oCTMTg6MzAiLCIxMDowMOKAkzE0OjAwIiwiQ2VycmFkbyJdLCJmIjoxMCwiZyI6WyI5IiwiNCIsIjUiXX0",
  },
  {
    parada: 39,
    bloque: "J2",
    hora: "16:10",
    nombre: "Zitada",
    tipo: "Peluquería",
    path: "/s/zitada?d=eyJuIjoiWml0YWRhIiwidCI6IlBlbHVxdWVyw61hIiwiZCI6IkdyYW4gVsOtYSBkZSBIb3J0YWxlemEsIDM3LCBIb3J0YWxlemEsIDI4MDQzIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTUgOTMgNjkgODkiLCJyIjo0LjcsImMiOjEwNywiaCI6Ii9hcGkvZm90bz9wbGFjZT1DaElKSVFlbzViNHZRZzBSQUlrWnhOelZOUkkmaT01IiwibyI6WyJDZXJyYWRvIiwiMTA6MDDigJMyMDowMCIsIjEwOjAw4oCTMjA6MDAiLCIxMDowMOKAkzIwOjAwIiwiMTA6MDDigJMyMDowMCIsIjEwOjAw4oCTMTQ6MDAiLCJDZXJyYWRvIl0sImYiOjEwLCJnIjpbIjAiLCIyIiwiNCIsIjEiXX0",
  },
  {
    parada: 40,
    bloque: "J2",
    hora: "16:35",
    nombre: "Peluqueria Palma",
    tipo: "Peluquería",
    path: "/s/peluqueria-palma?d=eyJuIjoiUGVsdXF1ZXJpYSBQYWxtYSIsInQiOiJQZWx1cXVlcsOtYSIsImQiOiJDLiBkZSBHb21lem5hcnJvLCBIb3J0YWxlemEsIDI4MDQzIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTMgMDAgMTEgNDgiLCJyIjo0LjcsImMiOjI3LCJoIjoiL2FwaS9mb3RvP3BsYWNlPUNoSUp6MnQ3M3RzdVFnMFJhQm85NlE4aVdfcyZpPTIiLCJvIjpbIjk6MzDigJMxNzozMCIsIjk6MzDigJMxNzozMCIsIjk6MzDigJMxNzozMCIsIjk6MzDigJMxNzozMCIsIjk6MzDigJMxNzozMCIsIjk6MDDigJMxMzowMCIsIkNlcnJhZG8iXSwiZiI6MTAsImciOlsiNCIsIjYiLCIzIiwiMCJdfQ",
  },
  {
    parada: 41,
    bloque: "J3",
    hora: "10:25",
    nombre: "Chispi Peluqueria de Señoras",
    tipo: "Peluquería de señoras",
    path: "/s/chispi-peluqueria-de-senoras?d=eyJuIjoiQ2hpc3BpIFBlbHVxdWVyaWEgZGUgU2XDsW9yYXMiLCJ0IjoiUGVsdXF1ZXLDrWEgZGUgc2XDsW9yYXMiLCJkIjoiQXYuIGRlIEJhcnJhbnF1aWxsYSwgMywgSG9ydGFsZXphLCAyODAzMyBNYWRyaWQsIEVzcGHDsWEiLCJwIjoiNjI5IDY2IDMyIDg3IiwiciI6NC43LCJjIjoxMywiaCI6Ii9hcGkvZm90bz9wbGFjZT1DaElKcThxamd3RXZRZzBSSVpvNFVsXzF5aXcmaT0zIiwibyI6WyI5OjMw4oCTMTQ6MzAiLCI5OjMw4oCTMTQ6MzAiLCI5OjMw4oCTMTQ6MzAiLCI5OjMw4oCTMTQ6MzAiLCI5OjMw4oCTMTQ6MzAiLCI5OjAw4oCTMTI6MDAiLCJDZXJyYWRvIl0sImYiOjEwLCJnIjpbIjIiLCI3IiwiOCIsIjAiXX0",
  },
  {
    parada: 42,
    bloque: "J3",
    hora: "10:45",
    nombre: "Laura Quero",
    tipo: "Peluquería y estética",
    path: "/s/laura-quero?d=eyJuIjoiTGF1cmEgUXVlcm8iLCJ0IjoiUGVsdXF1ZXLDrWEgeSBlc3TDqXRpY2EiLCJkIjoiQy4gZGVsIE1hciBkZSBPbcOhbiwgMzIsIEhvcnRhbGV6YSwgMjgwMzMgTWFkcmlkLCBFc3Bhw7FhIiwicCI6IjY1NSA0MCAzNyAzMSIsInIiOjQuOSwiYyI6MTI1LCJoIjoiL2FwaS9mb3RvP3BsYWNlPUNoSUpVMmFyNi1vdVFnMFJJeDlYYTdQOElVdyZpPTAiLCJvIjpbIkNlcnJhZG8iLCIxMDowMOKAkzE2OjMwIiwiMTA6MDDigJMxNjozMCIsIjEwOjAw4oCTMTY6MzAiLCI5OjMw4oCTMTk6MDAiLCI5OjMw4oCTMTQ6MDAiLCJDZXJyYWRvIl0sImYiOjEwLCJnIjpbIjEiLCIzIiwiMiIsIjQiXX0",
  },
  {
    parada: 43,
    bloque: "J3",
    hora: "11:05",
    nombre: "Peluqueria JAYSON",
    tipo: "Peluquería",
    path: "/s/peluqueria-jayson?d=eyJuIjoiUGVsdXF1ZXJpYSBKQVlTT04iLCJ0IjoiUGVsdXF1ZXLDrWEiLCJkIjoiQy4gZGVsIE1hciBBbWFyaWxsbywgNywgSG9ydGFsZXphLCAyODAzMyBNYWRyaWQsIEVzcGHDsWEiLCJwIjoiNjA3IDg3IDk5IDI0IiwiciI6NC45LCJjIjo4MywiaCI6Ii9hcGkvZm90bz9wbGFjZT1DaElKSDFsSm5Pb3VRZzBSbldTRUpjUHZUc2smaT01IiwibyI6WyIxMDowMOKAkzE5OjAwIiwiMTA6MDDigJMxOTowMCIsIjEwOjAw4oCTMTk6MDAiLCIxMDowMOKAkzE5OjAwIiwiMTA6MDDigJMxOTowMCIsIjEwOjAw4oCTMTQ6MDAiLCJDZXJyYWRvIl0sImYiOjgsImciOlsiMiIsIjAiLCIzIiwiMSJdfQ",
  },
  {
    parada: 44,
    bloque: "J3",
    hora: "11:25",
    nombre: "Melgar Peluqueros",
    tipo: "Peluquería",
    path: "/s/melgar-peluqueros?d=eyJuIjoiTWVsZ2FyIFBlbHVxdWVyb3MiLCJ0IjoiUGVsdXF1ZXLDrWEiLCJkIjoiQXYuIGRlIEJ1Y2FyYW1hbmdhLCAyLCBIb3J0YWxlemEsIDI4MDMzIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTcgNjMgMDIgMzUiLCJyIjo0LjcsImMiOjM0NiwiaCI6Ii9hcGkvZm90bz9wbGFjZT1DaElKVTJ0b0Zld3VRZzBScTQwdmRsNEtfVGMmaT04IiwibyI6WyI5OjMw4oCTMjA6MDAiLCI5OjMw4oCTMjA6MDAiLCI5OjMw4oCTMjA6MDAiLCI5OjMw4oCTMjA6MDAiLCI5OjMw4oCTMjA6MDAiLCI5OjAw4oCTMTQ6MDAiLCJDZXJyYWRvIl0sImYiOjEwLCJnIjpbIjEiLCI2IiwiNSIsIjkiXX0",
  },
  {
    parada: 45,
    bloque: "J3",
    hora: "11:45",
    nombre: "Blanco y Negro",
    tipo: "Barbería",
    path: "/s/blanco-y-negro?d=eyJuIjoiQmxhbmNvIHkgTmVncm8iLCJ0IjoiQmFyYmVyw61hIiwiZCI6IkMuIFBhaXBhLCAzLCBIb3J0YWxlemEsIDI4MDMzIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTcgNjMgNTUgOTIiLCJyIjo0LjgsImMiOjQyLCJoIjoiL2FwaS9mb3RvP3BsYWNlPUNoSUp0NVp4enUwdVFnMFJRYnpkTTdZajhJSSZpPTAiLCJvIjpbIkNlcnJhZG8iLCIxMDowMOKAkzE5OjAwIiwiMTA6MDDigJMxOTowMCIsIjEwOjAw4oCTMTk6MDAiLCIxMDowMOKAkzE5OjAwIiwiMTA6MDDigJMxNTowMCIsIkNlcnJhZG8iXSwiZiI6MX0",
  },
  {
    parada: 46,
    bloque: "J3",
    hora: "12:10",
    nombre: "Quka Perez - Peluquería",
    tipo: "Peluquería",
    path: "/s/quka-perez-peluqueria?d=eyJuIjoiUXVrYSBQZXJleiAtIFBlbHVxdWVyw61hIiwidCI6IlBlbHVxdWVyw61hIiwiZCI6IkMuIGRlIGxhcyBQZWRyb8OxZXJhcywgNDAsIEhvcnRhbGV6YSwgMjgwNDMgTWFkcmlkLCBFc3Bhw7FhIiwicCI6IjkxMyA4OCAzMSA2MCIsInIiOjQuOSwiYyI6MjgsImgiOiIvYXBpL2ZvdG8_cGxhY2U9Q2hJSk95RzBFX0F1UWcwUkNQdm9pU0UyazN3Jmk9MCIsIm8iOlsiMTA6MDDigJMxODozMCIsIjEwOjAw4oCTMTg6MzAiLCIxMDowMOKAkzE4OjMwIiwiMTA6MDDigJMxODozMCIsIjEwOjAw4oCTMTg6MzAiLCI5OjMw4oCTMTM6MzAiLCJDZXJyYWRvIl0sImYiOjF9",
  },
  {
    parada: 47,
    bloque: "J3",
    hora: "12:30",
    nombre: "María Plaza Centro de Belleza y Estética",
    tipo: "Peluquería y estética",
    path: "/s/maria-plaza-centro-de-belleza-y-estetica?d=eyJuIjoiTWFyw61hIFBsYXphIENlbnRybyBkZSBCZWxsZXphIHkgRXN0w6l0aWNhIiwidCI6IlBlbHVxdWVyw61hIHkgZXN0w6l0aWNhIiwiZCI6IkMuIGRlIFRyZWZhY2lvLCAxOSwgSG9ydGFsZXphLCAyODA0MyBNYWRyaWQsIEVzcGHDsWEiLCJwIjoiNjIyIDMwIDA1IDU1IiwiciI6NC44LCJjIjoxMDIsImgiOiIvYXBpL2ZvdG8_cGxhY2U9Q2hJSmUycHJvdTh1UWcwUmdaRU50cHhBZ3FZJmk9MCIsIm8iOlsiMTA6MDDigJMxNTozMCIsIkNlcnJhZG8iLCIxMDowMOKAkzE4OjAwIiwiMTA6MDDigJMxODozMCIsIjEwOjAw4oCTMTg6MzAiLCI5OjAw4oCTMTM6MDAiLCJDZXJyYWRvIl0sImYiOjYsImciOlsiMSIsIjQiLCI1IiwiMyJdfQ",
  },
  {
    parada: 48,
    bloque: "J3",
    hora: "12:50",
    nombre: "A.R peluquería y estética",
    tipo: "Peluquería y estética",
    path: "/s/a-r-peluqueria-y-estetica?d=eyJuIjoiQS5SIHBlbHVxdWVyw61hIHkgZXN0w6l0aWNhIiwidCI6IlBlbHVxdWVyw61hIHkgZXN0w6l0aWNhIiwiZCI6IkMuIGRlIFRyaWJhbGRvcywgNCwgSG9ydGFsZXphLCAyODA0MyBNYWRyaWQsIEVzcGHDsWEiLCJwIjoiOTE3IDU5IDI5IDcwIiwiciI6NC44LCJjIjoyMywiaCI6Ii9hcGkvZm90bz9wbGFjZT1DaElKWWNwaTBXc3ZRZzBSdXlnc0NlZTJ6Q00maT0xIiwibyI6WyIxMDowMOKAkzE0OjAwLCAxNTowMOKAkzE5OjAwIiwiMTA6MDDigJMxNDowMCwgMTU6MDDigJMxOTowMCIsIjEwOjAw4oCTMTQ6MDAsIDE1OjAw4oCTMTk6MDAiLCIxMDowMOKAkzE0OjAwLCAxNTowMOKAkzE5OjAwIiwiMTA6MDDigJMxNDowMCwgMTU6MDDigJMxOTowMCIsIjEwOjAw4oCTMTQ6MDAiLCJDZXJyYWRvIl0sImYiOjEwLCJnIjpbIjAiLCI0IiwiMiIsIjUiXX0",
  },
  {
    parada: 49,
    bloque: "J3",
    hora: "13:10",
    nombre: "New Vanity Peluqueros",
    tipo: "Peluquería",
    path: "/s/new-vanity-peluqueros?d=eyJuIjoiTmV3IFZhbml0eSBQZWx1cXVlcm9zIiwidCI6IlBlbHVxdWVyw61hIiwiZCI6IkMuIE1vdGlsbGEgZGVsIFBhbGFuY2FyLCAzLCBIb3J0YWxlemEsIDI4MDQzIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTAgODUgNjQgNDAiLCJyIjo0LjcsImMiOjc0LCJoIjoiL2FwaS9mb3RvP3BsYWNlPUNoSUp1N2ROUWVVdVFnMFJfcHRBRkxrNExKZyZpPTEiLCJvIjpbIjEwOjAw4oCTMTk6MDAiLCIxMDowMOKAkzE5OjAwIiwiMTA6MDDigJMxOTowMCIsIjEwOjAw4oCTMTk6MDAiLCIxMDowMOKAkzE5OjAwIiwiMTA6MDDigJMxNDowMCIsIkNlcnJhZG8iXSwiZiI6NSwiZyI6WyIwIiwiMiIsIjQiLCIzIl19",
  },
  {
    parada: 50,
    bloque: "J3",
    hora: "13:25",
    nombre: "Sara Llopis Peluquería y Estética",
    tipo: "Peluquería y estética",
    path: "/s/sara-llopis-peluqueria-y-estetica?d=eyJuIjoiU2FyYSBMbG9waXMgUGVsdXF1ZXLDrWEgeSBFc3TDqXRpY2EiLCJ0IjoiUGVsdXF1ZXLDrWEgeSBlc3TDqXRpY2EiLCJkIjoiQy4gZGUgTW90YSBkZWwgQ3VlcnZvLCA4LCBIb3J0YWxlemEsIDI4MDQzIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTIgODcgODMgNzYiLCJyIjo0LjcsImMiOjEwNCwiaCI6Ii9hcGkvZm90bz9wbGFjZT1DaElKUzlldXRlQXZRZzBSaGtMeXFYSmI2eFEmaT0xIiwibyI6WyI5OjMw4oCTMTQ6MDAiLCIxMDowMOKAkzE5OjAwIiwiMTA6MDDigJMxOTowMCIsIjEwOjAw4oCTMTk6MDAiLCIxMDowMOKAkzE5OjAwIiwiOTozMOKAkzEzOjMwIiwiQ2VycmFkbyJdLCJmIjo3LCJnIjpbIjAiLCI1IiwiMyJdfQ",
  },
  {
    parada: 51,
    bloque: "J4",
    hora: "15:00",
    nombre: "MA LARAS LIFESTYLE SALON & SPA",
    tipo: "Peluquería y estética",
    path: "/s/ma-laras-lifestyle-salon-spa?d=eyJuIjoiTUEgTEFSQVMgTElGRVNUWUxFIFNBTE9OICYgU1BBIiwidCI6IlBlbHVxdWVyw61hIHkgZXN0w6l0aWNhIiwiZCI6IkMuIGRlIFNpbHZhbm8sIDkyLCBIb3J0YWxlemEsIDI4MDQzIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTMgODggMzEgOTAiLCJyIjo0LjEsImMiOjgzLCJoIjoiL2FwaS9mb3RvP3BsYWNlPUNoSUpUN2VKa09ZdVFnMFIzNlA4Mk45XzNkVSZpPTMiLCJvIjpbIjEwOjAw4oCTMTk6MDAiLCIxMDowMOKAkzE5OjAwIiwiMTA6MDDigJMxOTowMCIsIjEwOjAw4oCTMTk6MDAiLCIxMDowMOKAkzE5OjAwIiwiMTA6MDDigJMxNDowMCIsIkNlcnJhZG8iXSwiZiI6MTAsImciOlsiNCIsIjAiLCIyIiwiMSJdfQ",
  },
  {
    parada: 52,
    bloque: "J4",
    hora: "15:25",
    nombre: "Mi Peluqueria Tatu",
    tipo: "Peluquería",
    path: "/s/mi-peluqueria-tatu?d=eyJuIjoiTWkgUGVsdXF1ZXJpYSBUYXR1IiwidCI6IlBlbHVxdWVyw61hIiwiZCI6IkMuIGRlIEFuZG9ycmEsIDk3LCBIb3J0YWxlemEsIDI4MDQzIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI2OTkgODMgOTEgNDgiLCJyIjo1LCJjIjoyMywiaCI6Ii9hcGkvZm90bz9wbGFjZT1DaElKbzI1LS1kMHVRZzBScEJ2bXJvakVTVUkmaT0wIiwibyI6WyI5OjMw4oCTMTY6MzAiLCI5OjMw4oCTMTY6MzAiLCI5OjMw4oCTMTY6MzAiLCI5OjMw4oCTMTY6MzAiLCI5OjMw4oCTMTg6MzAiLCI5OjMw4oCTMTQ6NDUiLCJDZXJyYWRvIl0sImYiOjEwLCJnIjpbIjUiLCI3IiwiMiIsIjgiXX0",
  },
  {
    parada: 53,
    bloque: "J4",
    hora: "16:00",
    nombre: "Cardedal La Peluquería De Caballeros",
    tipo: "Barbería",
    path: "/s/cardedal-la-peluqueria-de-caballeros?d=eyJuIjoiQ2FyZGVkYWwgTGEgUGVsdXF1ZXLDrWEgRGUgQ2FiYWxsZXJvcyIsInQiOiJCYXJiZXLDrWEiLCJkIjoiQXYuIGRlIE1hY2h1cGljaHUsIDE2LCBIb3J0YWxlemEsIDI4MDQzIE1hZHJpZCwgRXNwYcOxYSIsInAiOiI5MTcgMjEgOTYgMDAiLCJyIjo0LjYsImMiOjI2NSwiaCI6Ii9hcGkvZm90bz9wbGFjZT1DaElKS1RVY1RQNHVRZzBSMUF4R1RmRTFmbEkmaT03IiwibyI6WyI5OjMw4oCTMjA6MzAiLCI5OjMw4oCTMjA6MzAiLCI5OjMw4oCTMjA6MzAiLCI5OjMw4oCTMjA6MzAiLCI5OjMw4oCTMjA6MzAiLCI5OjE14oCTMTQ6MDAiLCJDZXJyYWRvIl0sImYiOjEwLCJnIjpbIjgiLCI2IiwiMiIsIjMiXX0",
  },
  {
    parada: 54,
    bloque: "J4",
    hora: "16:15",
    nombre: "Isabel Herrero Peluqueros",
    tipo: "Peluquería",
    path: "/s/isabel-herrero-peluqueros?d=eyJuIjoiSXNhYmVsIEhlcnJlcm8gUGVsdXF1ZXJvcyIsInQiOiJQZWx1cXVlcsOtYSIsImQiOiJBdi4gZGUgTWFjaHVwaWNodSwgMTYsIEhvcnRhbGV6YSwgMjgwNDMgTWFkcmlkLCBFc3Bhw7FhIiwicCI6IjkxNyA1OSA1OCA3NSIsInIiOjQuNiwiYyI6MTI4LCJoIjoiL2FwaS9mb3RvP3BsYWNlPUNoSUpLVFVjVFA0dVFnMFJKSS1CdUNMTkdwTSZpPTYiLCJvIjpbIjk6MDDigJMyMDozMCIsIjk6MDDigJMyMDozMCIsIjk6MDDigJMyMDozMCIsIjk6MDDigJMyMDozMCIsIjk6MDDigJMyMDozMCIsIjk6MDDigJMxODozMCIsIkNlcnJhZG8iXSwiZiI6MTAsImciOlsiMCIsIjciLCIzIiwiNCJdfQ",
  },
];
