/**
 * Cuarto corpus CIEGO (ronda 7c): 250 preguntas de un agente nuevo que solo vio
 * el catálogo y la guía de uso. Medido una sola vez con el motor congelado en
 * 897aee0. No se ajusta nada mirando sus fallos.
 */
export const CORPUS_CIEGO_4: Array<[string, string]> = [
  ["cuantas citas tenemos hoy en total?", "citas-hoy"],
  ["hoy cuantas citas hay repartidas por cada una", "citas-hoy"],
  ["cuantas citas tiene sara hoy?", "citas-hoy-profesional"],
  ["a noelia cuantas le quedan hoy y cual es la siguiente", "citas-hoy-profesional"],
  ["quien esta ahora mismo en silla?", "proxima-cita"],
  ["quien viene despues de esta clienta", "proxima-cita"],
  ["pasame la lista de lo que queda hoy por horas", "lista-citas-hoy"],
  ["que nos queda hoy, con las horas de cada una", "lista-citas-hoy"],
  ["cuantos huecos de 30 min o mas quedan hoy y de quien son", "huecos-hoy"],
  ["hoy cuanto tiempo libre nos queda en total", "huecos-hoy"],
  ["que % llevamos ocupado hoy", "ocupacion-hoy"],
  ["como de llena esta la jornada de hoy", "ocupacion-hoy"],
  ["cuanto vale el dia de hoy", "ingresos-hoy"],
  ["hoy cuanto llevamos cobrado y cuanto falta", "ingresos-hoy"],
  ["que tengo pendiente de mirar yo?", "pendiente-de-ti"],
  ["que me esta esperando a mi ahora mismo", "pendiente-de-ti"],
  ["hay solicitudes de la web sin confirmar?", "solicitudes-pendientes"],
  ["cuantas reservas nuevas estan esperando que las confirme", "solicitudes-pendientes"],
  ["que citas de hoy faltan por marcar si vinieron", "por-marcar"],
  ["cuales tengo sin poner vino o no vino", "por-marcar"],
  ["estamos abiertas ahora?", "abierto-ahora"],
  ["hasta que hora abrimos hoy", "abierto-ahora"],
  ["quien trae color hoy y con que formula", "colores-hoy"],
  ["a quien de hoy le falta anotar el color", "colores-hoy"],
  ["que citas hay el jueves", "citas-dia"],
  ["dime las citas del lunes", "citas-dia"],
  ["manana que tenemos, por horas", "citas-manana"],
  ["las citas de mañana como van repartidas", "citas-manana"],
  ["que huecos hay el martes por profesional", "huecos-dia"],
  ["huecos libres del miercoles, de cada una", "huecos-dia"],
  ["primer hueco que haya libre para un tinte", "primer-hueco-servicio"],
  ["cuando es el primer hueco libre para unas mechas", "primer-hueco-servicio"],
  ["cuando tiene hueco maria esta semana", "hueco-profesional"],
  ["sara cuando le queda un hueco libre", "hueco-profesional"],
  ["cuantas citas hemos tenido esta semana frente a la anterior", "citas-periodo"],
  ["en septiembre cuantas citas llevamos", "citas-periodo"],
  ["la ocupacion media de este mes cual es", "ocupacion-periodo"],
  ["que ocupacion llevamos esta semana entre todas", "ocupacion-periodo"],
  ["cuando viene {C} otra vez?", "proxima-cita-clienta"],
  ["{C} cuando tiene la proxima cita", "proxima-cita-clienta"],
  ["a quien hay que mandar recordatorio de manana", "recordatorios-manana"],
  ["recordatorios de mañana, a quien le falta enviarselo", "recordatorios-manana"],
  ["quien esta en lista de espera y para que servicio", "lista-espera"],
  ["hay alguien en espera ahora mismo?", "lista-espera"],
  ["que franja horaria es la mas floja ultimamente", "franja-floja"],
  ["cual es la hora que menos se llena normalmente", "franja-floja"],
  ["que dia de esta semana esta mas lleno", "dia-mas-lleno"],
  ["cual fue el dia con mas citas en septiembre", "dia-mas-lleno"],
  ["cuantas cancelaciones llevamos esta semana", "cancelaciones"],
  ["cancelaciones del mes pasado, cuantas hubo", "cancelaciones"],
  ["cuantos plantones llevamos este mes y quien repite", "plantones"],
  ["quien no vino o llego tarde esta semana", "plantones"],
  ["que se hizo {C} la ultima vez y con quien", "ultima-visita-clienta"],
  ["ultima visita de {C}, que se hizo exactamente", "ultima-visita-clienta"],
  ["que formula de color tiene apuntada {C}", "ultimo-color-clienta"],
  ["cual es el ultimo color de {C}", "ultimo-color-clienta"],
  ["cada cuanto suele venir {C}", "frecuencia-clienta"],
  ["con que frecuencia viene {C} por aqui", "frecuencia-clienta"],
  ["cuanto se ha gastado {C} en total", "gasto-clienta"],
  ["gasto aproximado de {C} este año", "gasto-clienta"],
  ["el telefono de {C} cual es", "datos-clienta"],
  ["pasame correo y cumple de {C}", "datos-clienta"],
  ["que notas tiene {C} en la ficha", "notas-clienta"],
  ["hay algun aviso apuntado de {C}?", "notas-clienta"],
  ["cuantas clientas tenemos en total", "clientas-total"],
  ["cuantas fichas de clientas hay ahora mismo", "clientas-total"],
  ["clientas nuevas de este mes, cuantas y quienes", "clientas-nuevas"],
  ["quien vino por primera vez esta semana", "clientas-nuevas"],
  ["que porcentaje de clientas son recurrentes", "clientas-recurrentes"],
  ["cuantas clientas repiten normalmente", "clientas-recurrentes"],
  ["quien lleva mucho sin venir por el salon", "clientas-inactivas"],
  ["cuantas clientas estan paradas hace tiempo", "clientas-inactivas"],
  ["quienes son las clientas que mas gastan", "mejores-clientas"],
  ["dame el top de clientas por gasto", "mejores-clientas"],
  ["a quien de las citadas le falta anotar el color", "color-pendiente"],
  ["quien tiene color pendiente de apuntar", "color-pendiente"],
  ["quien cumple años este mes", "cumpleanos"],
  ["cumpleaños de esta semana, quien es", "cumpleanos"],
  ["quien nos debe algo pendiente", "clientas-con-deuda"],
  ["cuanto suman los recargos pendientes", "clientas-con-deuda"],
  ["{C} puede reservar por la web o esta bloqueada?", "clienta-bloqueada"],
  ["esta bloqueada {C} para reservar online", "clienta-bloqueada"],
  ["buscame la ficha de {C}", "buscar-clienta"],
  ["abreme a {C}, no me acuerdo del telefono", "buscar-clienta"],
  ["el horario de noelia cual es", "horario-profesional"],
  ["que dias trabaja sara a la semana", "horario-profesional"],
  ["quien trabaja el jueves", "quien-trabaja"],
  ["quien esta el lunes que viene", "quien-trabaja"],
  ["cuantas citas ha hecho maria esta semana", "citas-profesional-periodo"],
  ["citas de sara en septiembre, cuantas fueron", "citas-profesional-periodo"],
  ["que ocupacion lleva noelia este mes", "ocupacion-profesional"],
  ["como de llena va maria esta semana", "ocupacion-profesional"],
  ["cuanto lleva cobrado sara este mes", "dinero-profesional"],
  ["lo previsto de maria para esta semana, cuanto es", "dinero-profesional"],
  ["que servicio hace mas noelia", "lo-que-mas-hace"],
  ["lo que mas hace sara normalmente cual es", "lo-que-mas-hace"],
  ["con quien suele ir {C}", "profesional-habitual"],
  ["{C} con cual de nosotras va siempre", "profesional-habitual"],
  ["cuanto cuesta el corte", "precio-servicio"],
  ["precio de las mechas cual es", "precio-servicio"],
  ["cuanto dura un tinte segun la carta", "duracion-servicio"],
  ["el tratamiento cuanto tiempo lleva de verdad", "duracion-servicio"],
  ["que servicio se pide mas este mes", "servicio-mas-pedido"],
  ["cual es el servicio mas solicitado en septiembre", "servicio-mas-pedido"],
  ["que servicio deja mas pasta por hora de trabajo", "servicio-mas-rentable"],
  ["cual es el mas rentable por hora trabajada", "servicio-mas-rentable"],
  ["que servicios tenemos en la carta", "carta"],
  ["que se puede reservar por la pagina de todo lo que hacemos", "carta"],
  ["cuantas veces hemos hecho recogidos este mes y cuanto dejo", "veces-servicio"],
  ["el peinado de novia cuantas veces se hizo en septiembre y lo que dejo", "veces-servicio"],
  ["cuanto hemos cobrado esta semana", "cobrado-periodo"],
  ["lo cobrado el mes pasado, cuanto fue", "cobrado-periodo"],
  ["cuanto tenemos previsto para la semana que viene", "previsto-periodo"],
  ["lo previsto de este mes cuanto suma", "previsto-periodo"],
  ["como vamos a cerrar el mes", "estimacion-mes"],
  ["estimacion de cierre de septiembre cual es", "estimacion-mes"],
  ["cuanto entro por bizum esta semana", "cobro-por-metodo"],
  ["reparto de cobro por tarjeta efectivo y bizum del mes pasado", "cobro-por-metodo"],
  ["como vamos este mes comparado con el anterior en general", "comparar-periodos"],
  ["compara esta semana con la semana pasada", "comparar-periodos"],
  ["cual es el ticket medio de este mes", "precio-medio"],
  ["precio medio por cita de esta semana", "precio-medio"],
  ["cuanto ha dejado el tinte este mes", "dinero-servicio"],
  ["lo que deja mechas segun tarifa, cuanto es", "dinero-servicio"],
  ["pasame el resumen del mes", "resumen-mes"],
  ["como me sacas el resumen de septiembre en excel", "resumen-mes"],
  ["que señales estan pedidas y sin llegar", "senales-pendientes"],
  ["señales pendientes de cobrar cuales son", "senales-pendientes"],
  ["que señales se han pasado de plazo sin pagar", "senales-vencidas"],
  ["señales vencidas ahora mismo cuantas hay", "senales-vencidas"],
  ["{C} ha pagado ya la señal de su cita?", "senal-cita"],
  ["como va la señal de la cita de {C}", "senal-cita"],
  ["cuanto pedimos de señal y a quien", "regla-senal"],
  ["que plazo tenemos puesto para la señal", "regla-senal"],
  ["cuantas señales hemos recibido esta semana y cuanto suman", "senales-recibidas"],
  ["señales cobradas el mes pasado, cuanto sumaron", "senales-recibidas"],
  ["que campaña me conviene lanzar ahora", "campanas"],
  ["a cuanta gente le llegaria una campaña de cumpleaños", "campanas"],
  ["cuantas clientas se pueden recuperar este mes", "recuperables"],
  ["cuantos huecos recuperables hay este mes", "recuperables"],
  ["a quien le ofrezco los huecos flojos que tenemos", "huecos-flojos"],
  ["que huecos flojos hay y a quien se los mando", "huecos-flojos"],
  ["que clientas nuevas no han vuelto todavia", "segunda-visita"],
  ["quien vino una vez y no ha repetido", "segunda-visita"],
  ["a quien le pido una reseña de google", "resenas"],
  ["quien seria buena para pedirle una reseña", "resenas"],
  ["el horario del salon cual es", "horario-salon"],
  ["a que hora abrimos y cerramos entre semana", "horario-salon"],
  ["pasame el enlace de reservas para compartir", "enlace-reservas"],
  ["cual es el link de la pagina para poner en instagram", "enlace-reservas"],
  ["que pone la web sobre cancelar una cita", "politica-cancelacion"],
  ["cual es nuestra politica de cancelacion", "politica-cancelacion"],
  ["que le preguntamos a la clienta cuando reserva", "preguntas-reserva"],
  ["que datos pide el formulario de reserva", "preguntas-reserva"],
  ["hay penalizacion si no vienen a la cita?", "plantones-config"],
  ["cuanto se cobra si hacen un plantón", "plantones-config"],
  ["como es el mensaje de confirmacion que se manda", "mensajes-whatsapp"],
  ["que texto lleva el recordatorio de whatsapp", "mensajes-whatsapp"],
  ["la duracion de la cita se pone al aceptar la solicitud?", "duracion-flexible"],
  ["quien decide cuanto dura cada solicitud nueva", "duracion-flexible"],
  ["puedo ver las citas en el calendario del iphone?", "calendario-suscrito"],
  ["como activo que salgan las citas en google calendar", "calendario-suscrito"],
  ["que color tiene cada profesional en el calendario", "equipo-y-colores"],
  ["de que color pinta el tinte en el calendario", "equipo-y-colores"],
  ["que tipo de cosas te puedo preguntar", "que-puedo-preguntar"],
  ["dame ejemplos de preguntas que se te puedan hacer", "que-puedo-preguntar"],
  ["como te tengo que preguntar para que me entiendas mejor", "como-preguntar"],
  ["algun consejo para preguntarte bien", "como-preguntar"],
  ["buenas!", "saludo"],
  ["hola buenos dias", "saludo"],
  ["gracias!!", "gracias"],
  ["muchas gracias por la ayuda", "gracias"],
  ["tu quien eres exactamente?", "quien-eres"],
  ["que cosas sabes hacer tu", "que-sabes-hacer"],
  ["que puedes hacer por mi", "que-sabes-hacer"],
  ["me voy, hasta luego", "despedida"],
  ["que bien lo estas haciendo", "buen-trabajo"],
  ["vaya crack estas hecho", "buen-trabajo"],
  ["que tal estas?", "como-estas"],
  ["no te entiendo nada de lo que dices", "no-entiendo"],
  ["quiero hablar con una persona de verdad", "ayuda-humana"],
  ["cuentame un chiste", "broma"],
  ["echame unas risas anda", "broma"],
  ["puedo meter mas de 3 profesionales en mi plan?", "plan-mas-profesionales"],
  ["cuantas profesionales caben en mi plan actual", "plan-mas-profesionales"],
  ["la carta de mi pagina se puede separar por categorias?", "plan-segunda-pagina"],
  ["puedo tener mi propio dominio para la pagina de reservas?", "plan-dominio-propio"],
  ["se puede sacar un informe mensual descargable?", "plan-informe-mensual"],
  ["los mensajes de whatsapp se mandan solos automaticamente?", "plan-whatsapp-automatico"],
  ["los recordatorios de mañana se envian automaticos o los mando yo?", "plan-recordatorio-automatico"],
  ["puedo importar el excel del tpv cuando yo quiera o solo una vez?", "plan-importar-mensual"],
  ["el asistente viene incluido en mi plan?", "plan-asistente"],
  ["por que no me deja preguntar al asistente, no lo tengo contratado?", "plan-asistente"],
  ["siShow me saca las facturas?", "no-hace-facturas"],
  ["puedo facturar desde aqui o eso sigue en el tpv?", "no-hace-facturas"],
  ["se puede cobrar la señal con tarjeta?", "no-cobra-tarjeta"],
  ["si cambio algo en mi google calendar se actualiza aqui tambien?", "no-escribe-google"],
  ["las campañas de marketing se mandan solas sin que yo las vea?", "no-campanas-automaticas"],
  ["como creo una cita nueva desde el movil", "tec-crear-cita"],
  ["donde le doy para meter una cita nueva", "tec-crear-cita"],
  ["como cambio la hora de una cita ya puesta", "tec-mover-cita"],
  ["quiero mover una cita a otro dia, como se hace", "tec-mover-cita"],
  ["como confirmo una solicitud que ha llegado", "tec-confirmar"],
  ["donde le doy para confirmar una peticion de la web", "tec-confirmar"],
  ["como anulo una cita del calendario", "tec-cancelar"],
  ["como rechazo una solicitud que no me viene bien", "tec-cancelar"],
  ["donde apunto la formula de color de una clienta", "tec-anotar-color"],
  ["como guardo el color que le hemos hecho hoy", "tec-anotar-color"],
  ["como importo el excel del tpv en clientas", "tec-importar-tpv"],
  ["por donde subo el archivo del tpv 123", "tec-importar-tpv"],
  ["como pido la señal por whatsapp a una clienta", "tec-senal"],
  ["donde marco que la señal ya se ha enviado", "tec-senal"],
  ["donde cambio el horario del salon", "tec-horario"],
  ["como pongo el horario nuevo de noelia", "tec-horario"],
  ["como cambio el precio de un servicio", "tec-precios"],
  ["donde añado un servicio nuevo a la carta", "tec-precios"],
  ["no me estan llegando reservas por la web, que reviso", "tec-no-llegan-reservas"],
  ["porque no entra ninguna solicitud nueva desde ayer", "tec-no-llegan-reservas"],
  ["no encuentro una cita que se que existe, donde miro", "tec-no-sale-cita"],
  ["no me aparece la cita de esta manana, que hago", "tec-no-sale-cita"],
  ["le doy a mandar whatsapp y no me abre nada", "tec-whatsapp-no-abre"],
  ["por que no me abre whatsapp al pulsar el boton", "tec-whatsapp-no-abre"],
  ["el panel va lentisimo, que hago", "tec-panel-lento"],
  ["se ha quedado colgada la pantalla, como lo arreglo", "tec-panel-lento"],
  ["no me llega el enlace para entrar, que hago", "tec-contrasena"],
  ["que tiempo va a hacer mañana en madrid", "no-se"],
  ["cuanto es el 15% de 340", "no-se"],
  ["receta facil de tortilla de patatas", "no-se"],
  ["quien gano el partido del madrid ayer", "no-se"],
  ["¿como saco cita para el dni?", "no-se"],
  ["cuanto cuesta un vuelo a lisboa", "no-se"],
  ["que pelicula ponen hoy en el cine", "no-se"],
  ["¿como se hace la declaracion de la renta?", "no-se"],
  ["cual es la capital de portugal", "no-se"],
  ["que hora es en nueva york ahora mismo", "no-se"],
  ["como actualizo el iphone a la ultima version", "no-se"],
  ["cuantos gramos son una taza de harina", "no-se"],
  ["donde aparco cerca de sol", "no-se"],
  ["¿que se necesita para renovar el pasaporte?", "no-se"],
  ["cual es el precio de la gasolina hoy", "no-se"],
  ["como resincronizo mis auriculares bluetooth", "no-se"],
  ["cuanto tarda un paquete de amazon en llegar", "no-se"],
  ["que dias hay huelga de metro esta semana", "no-se"],
  ["como convierto libras a kilos", "no-se"],
  ["recomiendame un restaurante italiano por el centro", "no-se"],
  ["¿que serie me recomiendas ver esta noche?", "no-se"],
  ["como cambio el idioma del movil", "no-se"],
  ["cual es la mejor epoca para viajar a japon", "no-se"],
  ["cuanto tarda en cocerse un huevo duro", "no-se"],
  ["¿que necesito para dar de alta un autonomo?", "no-se"],
];
