/**
 * Segundo corpus CIEGO: 250 preguntas de otro agente que solo vio el catálogo
 * (ids y qué responde cada una). Se escribió cuando el motor ya estaba
 * congelado y se midió una sola vez, sin ajustar nada después. Es la cifra de
 * generalización del lote 7.
 */
export const CORPUS_CIEGO_2: Array<[string, string]> = [
  ["cuantas citas hay hoy?", "citas-hoy"],
  ["¿Cómo se reparte hoy el trabajo entre el equipo?", "citas-hoy"],
  ["cuantas citas tiene sara hoy", "citas-hoy-profesional"],
  ["que le queda a noelia hoy y cual es la siguiente?", "citas-hoy-profesional"],
  ["quien esta ahora mismo en el sillon", "proxima-cita"],
  ["¿quién viene justo después de la clienta que está ahora?", "proxima-cita"],
  ["pasame la lista de lo que queda hoy por horas", "lista-citas-hoy"],
  ["que tenemos hoy de aqui a cierre, con hora porfa", "lista-citas-hoy"],
  ["cuantos huecos libres de media hora quedan hoy?", "huecos-hoy"],
  ["que huecos tenemos hoy y de quien son", "huecos-hoy"],
  ["que % de hoy esta ya ocupado", "ocupacion-hoy"],
  ["¿cómo de llena va la jornada de hoy?", "ocupacion-hoy"],
  ["cuanto vale el dia de hoy", "ingresos-hoy"],
  ["cuanto llevamos cobrado hoy y cuanto falta por cobrar", "ingresos-hoy"],
  ["que tengo pendiente de revisar hoy", "pendiente-de-ti"],
  ["¿qué me espera hoy, solicitudes y demás?", "pendiente-de-ti"],
  ["hay solicitudes nuevas de la web?", "solicitudes-pendientes"],
  ["cuantas reservas online estan sin confirmar", "solicitudes-pendientes"],
  ["que citas faltan por marcar si vinieron", "por-marcar"],
  ["que citas de esta semana me faltan por marcar", "por-marcar"],
  ["¿estamos abiertos ahora mismo?", "abierto-ahora"],
  ["hasta que hora abrimos hoy", "abierto-ahora"],
  ["quien lleva color hoy y con que formula", "colores-hoy"],
  ["a quien le falta la formula del color de hoy", "colores-hoy"],
  ["que citas hay el martes", "citas-dia"],
  ["cuantas citas hay el lunes", "citas-dia"],
  ["que tenemos mñn por la mañana", "citas-manana"],
  ["pasame las citas de mañana con hora", "citas-manana"],
  ["que huecos hay el miercoles por profesional", "huecos-dia"],
  ["huecos del jueves, quien tiene libre", "huecos-dia"],
  ["¿cuándo es el primer hueco para un tinte?", "primer-hueco-servicio"],
  ["primer hueco libre para mechas, cuando", "primer-hueco-servicio"],
  ["cuando tiene hueco maria esta semana", "hueco-profesional"],
  ["sara cuando tiene un rato libre la semana que viene", "hueco-profesional"],
  ["cuantas citas llevamos este mes", "citas-periodo"],
  ["cuantas citas hubo la semana pasada", "citas-periodo"],
  ["que ocupacion media llevamos este mes", "ocupacion-periodo"],
  ["como de ocupados hemos ido esta semana", "ocupacion-periodo"],
  ["cuando viene {C} otra vez", "proxima-cita-clienta"],
  ["¿{C} tiene cita esta semana?", "proxima-cita-clienta"],
  ["a quien tengo que recordar la cita de mañana", "recordatorios-manana"],
  ["lista de recordatorios para mñn", "recordatorios-manana"],
  ["quien esta en lista de espera", "lista-espera"],
  ["para que servicio hay gente esperando hueco", "lista-espera"],
  ["que franja horaria tenemos mas floja", "franja-floja"],
  ["a que hora se nos queda mas vacio el salon", "franja-floja"],
  ["que dia ha sido el mas lleno este mes", "dia-mas-lleno"],
  ["cual es la hora con mas citas de septiembre", "dia-mas-lleno"],
  ["cuantas cancelaciones llevamos este mes", "cancelaciones"],
  ["cuantas citas se cancelaron la semana pasada", "cancelaciones"],
  ["cuantos plantones llevamos este mes", "plantones"],
  ["quien repite en no presentarse", "plantones"],
  ["que se hizo {C} la ultima vez", "ultima-visita-clienta"],
  ["ultima visita de {C}, con quien fue", "ultima-visita-clienta"],
  ["que formula de color tiene apuntada {C}", "ultimo-color-clienta"],
  ["cual es el ultimo color de {C}", "ultimo-color-clienta"],
  ["cada cuanto suele venir {C}", "frecuencia-clienta"],
  ["con que frecuencia viene {C} por aqui", "frecuencia-clienta"],
  ["cuanto se ha gastado {C} con nosotras", "gasto-clienta"],
  ["gasto total de {C} mas o menos", "gasto-clienta"],
  ["pasame el telefono de {C}", "datos-clienta"],
  ["cual es el cumple de {C}", "datos-clienta"],
  ["que notas tiene {C} en la ficha", "notas-clienta"],
  ["hay algun aviso apuntado de {C}?", "notas-clienta"],
  ["cuantas clientas tenemos en total", "clientas-total"],
  ["cuantas fichas de clientas hay", "clientas-total"],
  ["cuantas clientas nuevas han venido este mes", "clientas-nuevas"],
  ["quien vino por primera vez la semana pasada", "clientas-nuevas"],
  ["que parte de las clientas son recurrentes", "clientas-recurrentes"],
  ["cuantas clientas repiten habitualmente", "clientas-recurrentes"],
  ["quien lleva mucho sin venir", "clientas-inactivas"],
  ["cuantas clientas estan paradas sin pisar el salon", "clientas-inactivas"],
  ["quienes son las clientas que mas gastan", "mejores-clientas"],
  ["el top de clientas por gasto cual es", "mejores-clientas"],
  ["a quien le falta anotar el color antes de su cita", "color-pendiente"],
  ["quien tiene cita pronto y sin color apuntado", "color-pendiente"],
  ["quien cumple años este mes", "cumpleanos"],
  ["cumpleaños de septiembre, quien hay", "cumpleanos"],
  ["quien me debe algo pendiente", "clientas-con-deuda"],
  ["cuanto suman los recargos pendientes", "clientas-con-deuda"],
  ["¿{C} puede reservar por internet?", "clienta-bloqueada"],
  ["esta bloqueada {C} para reservar online", "clienta-bloqueada"],
  ["buscame la ficha de {C}", "buscar-clienta"],
  ["encuentra a {C} en el sistema", "buscar-clienta"],
  ["que horario tiene noelia esta semana", "horario-profesional"],
  ["dime el horario semanal de sara", "horario-profesional"],
  ["quien trabaja el lunes", "quien-trabaja"],
  ["quien viene a currar el jueves", "quien-trabaja"],
  ["cuantas citas ha hecho maria este mes", "citas-profesional-periodo"],
  ["citas de sara la semana pasada", "citas-profesional-periodo"],
  ["como de ocupada va noelia este mes", "ocupacion-profesional"],
  ["ocupacion de maria esta semana", "ocupacion-profesional"],
  ["cuanto lleva cobrado sara este mes", "dinero-profesional"],
  ["cuanto tiene previsto maria esta semana", "dinero-profesional"],
  ["que es lo que mas hace noelia", "lo-que-mas-hace"],
  ["servicio estrella de maria cual es", "lo-que-mas-hace"],
  ["con quien suele ir {C}", "profesional-habitual"],
  ["quien atiende normalmente a {C}", "profesional-habitual"],
  ["cuanto cuesta el tinte", "precio-servicio"],
  ["precio de las mechas cual es", "precio-servicio"],
  ["cuanto dura un corte normalmente", "duracion-servicio"],
  ["cuanto tiempo real lleva un recogido", "duracion-servicio"],
  ["cual es el servicio mas pedido este mes", "servicio-mas-pedido"],
  ["que se pide mas en septiembre", "servicio-mas-pedido"],
  ["que servicio es el mas rentable por hora", "servicio-mas-rentable"],
  ["cual nos deja mas pasta por hora de curro", "servicio-mas-rentable"],
  ["que servicios tenemos en la carta", "carta"],
  ["que se puede reservar desde la web", "carta"],
  ["cuantas veces hemos hecho tratamiento este mes y cuanto ha dejado", "veces-servicio"],
  ["veces que se ha hecho peinado de novia en septiembre", "veces-servicio"],
  ["cuanto hemos cobrado esta semana", "cobrado-periodo"],
  ["total cobrado el mes pasado", "cobrado-periodo"],
  ["cuanto tenemos previsto para la semana que viene", "previsto-periodo"],
  ["cuanto llevamos previsto para septiembre", "previsto-periodo"],
  ["como vamos a acabar el mes", "estimacion-mes"],
  ["estimacion de cierre de este mes", "estimacion-mes"],
  ["cuanto llevamos por bizum este mes", "cobro-por-metodo"],
  ["cuanto hemos cobrado en efectivo esta semana", "cobro-por-metodo"],
  ["como va este mes comparado con el anterior", "comparar-periodos"],
  ["septiembre como queda frente al mes pasado", "comparar-periodos"],
  ["cual es el ticket medio de este mes", "precio-medio"],
  ["precio medio por cita esta semana", "precio-medio"],
  ["cuanto ha dejado el tinte este mes", "dinero-servicio"],
  ["lo que ha generado el recogido en septiembre", "dinero-servicio"],
  ["hazme el resumen del mes", "resumen-mes"],
  ["pasame el resumen de septiembre", "resumen-mes"],
  ["que señales estan pendientes de llegar", "senales-pendientes"],
  ["señales que faltan por cobrar cuales son", "senales-pendientes"],
  ["que señales se han pasado de plazo", "senales-vencidas"],
  ["señales vencidas sin cobrar cuales hay", "senales-vencidas"],
  ["¿ha pagado la señal {C}?", "senal-cita"],
  ["como va la señal de la cita de {C}", "senal-cita"],
  ["cuanto pedimos de señal y a quien", "regla-senal"],
  ["cual es el plazo para la señal", "regla-senal"],
  ["cuanto hemos recibido de señales este mes", "senales-recibidas"],
  ["señales cobradas la semana pasada cuantas fueron", "senales-recibidas"],
  ["que campaña me recomiendas lanzar", "campanas"],
  ["a cuanta gente le vendria bien una campaña ahora", "campanas"],
  ["cuantas clientas puedo recuperar este mes", "recuperables"],
  ["que huecos son recuperables este mes", "recuperables"],
  ["a quien le ofrezco los huecos flojos", "huecos-flojos"],
  ["quien podria venir a llenarme el hueco flojo de la tarde", "huecos-flojos"],
  ["que clientas nuevas no han vuelto todavia", "segunda-visita"],
  ["quien vino una vez y no ha repetido", "segunda-visita"],
  ["a quien le pido una reseña", "resenas"],
  ["quien me puede dejar una reseña buena", "resenas"],
  ["que horario tenemos de apertura", "horario-salon"],
  ["a que hora abrimos entre semana", "horario-salon"],
  ["pasame el enlace de reservas", "enlace-reservas"],
  ["el link para que reserven online cual es", "enlace-reservas"],
  ["que pone la web sobre cancelaciones", "politica-cancelacion"],
  ["cual es nuestra politica de cancelacion", "politica-cancelacion"],
  ["que le preguntamos a la clienta al reservar", "preguntas-reserva"],
  ["que datos pedimos en la reserva online", "preguntas-reserva"],
  ["¿tenemos penalizacion por no presentarse?", "plantones-config"],
  ["cuanto se cobra si hay plantón", "plantones-config"],
  ["como es el mensaje de confirmacion que mandamos", "mensajes-whatsapp"],
  ["que pone el whatsapp de recordatorio", "mensajes-whatsapp"],
  ["¿la duracion se decide cuando acepto la solicitud?", "duracion-flexible"],
  ["puedo ajustar la duracion al aceptar la cita", "duracion-flexible"],
  ["como hago para ver las citas en el calendario del movil", "calendario-suscrito"],
  ["como activo la sincronizacion con mi iphone", "calendario-suscrito"],
  ["que color tiene cada profesional en el calendario", "equipo-y-colores"],
  ["de que color sale el tinte en la agenda", "equipo-y-colores"],
  ["que cosas te puedo preguntar", "que-puedo-preguntar"],
  ["dame ejemplos de lo que sabes contestar", "que-puedo-preguntar"],
  ["como te tengo que preguntar para que entiendas", "como-preguntar"],
  ["algun truco para preguntarte mejor", "como-preguntar"],
  ["buenos dias!", "saludo"],
  ["hola que tal", "saludo"],
  ["gracias majo", "gracias"],
  ["mil gracias por la ayuda", "gracias"],
  ["me voy, hasta luego", "despedida"],
  ["venga, adios", "despedida"],
  ["que sabes hacer tu", "que-sabes-hacer"],
  ["para que sirves exactamente", "que-sabes-hacer"],
  ["tu quien eres exactamente", "quien-eres"],
  ["eres una persona o un robot", "quien-eres"],
  ["que bien llevas esto, chapo", "buen-trabajo"],
  ["que tal estas hoy", "como-estas"],
  ["no he entendido lo q me has dicho antes", "no-entiendo"],
  ["quiero hablar con una persona de soporte", "ayuda-humana"],
  ["cuentame un chiste anda", "broma"],
  ["hasta cuantas profesionales me deja tener el plan", "plan-mas-profesionales"],
  ["puedo meter mas de 3 en el equipo con mi plan?", "plan-mas-profesionales"],
  ["se puede separar la carta por categorias en mi pagina", "plan-segunda-pagina"],
  ["puedo usar mi propio dominio para las reservas online?", "plan-dominio-propio"],
  ["puedo descargarme el resumen del mes?", "plan-informe-mensual"],
  ["el informe mensual esta incluido en mi plan?", "plan-informe-mensual"],
  ["los mensajes de whatsapp se mandan solos?", "plan-whatsapp-automatico"],
  ["los recordatorios se envian automaticos o los mando yo", "plan-recordatorio-automatico"],
  ["los recordatorios se mandan todos juntos o uno a uno?", "plan-recordatorio-automatico"],
  ["puedo importar el excel del tpv cuando quiera", "plan-importar-mensual"],
  ["el asistente viene incluido en el plan reservas?", "plan-asistente"],
  ["puedo sacar facturas desde aqui?", "no-hace-facturas"],
  ["se puede cobrar la señal con tarjeta?", "no-cobra-tarjeta"],
  ["si cambio algo en el google calendar se actualiza aqui tambien?", "no-escribe-google"],
  ["las campañas se mandan solas o las envio yo", "no-campanas-automaticas"],
  ["como creo una cita nueva", "tec-crear-cita"],
  ["donde le doy para meter una cita", "tec-crear-cita"],
  ["como cambio la hora de una cita", "tec-mover-cita"],
  ["quiero mover una cita a otro dia, como se hace", "tec-mover-cita"],
  ["como confirmo una cita de hoy", "tec-confirmar"],
  ["donde le doy para confirmar la cita", "tec-confirmar"],
  ["como cancelo una cita", "tec-cancelar"],
  ["como rechazo una solicitud", "tec-cancelar"],
  ["donde anoto el color de una clienta", "tec-anotar-color"],
  ["como meto la formula de tinte en la ficha", "tec-anotar-color"],
  ["como importo el excel del tpv", "tec-importar-tpv"],
  ["de donde subo el excel de clientas", "tec-importar-tpv"],
  ["como pido la señal por whatsapp", "tec-senal"],
  ["donde configuro la regla de la señal", "tec-senal"],
  ["donde cambio el horario del salon", "tec-horario"],
  ["como edito el horario de una profesional", "tec-horario"],
  ["donde cambio el precio de un servicio", "tec-precios"],
  ["como añado un servicio nuevo con su precio", "tec-precios"],
  ["no me llegan reservas por la web, que reviso", "tec-no-llegan-reservas"],
  ["llevo dias sin solicitudes nuevas, q puede pasar", "tec-no-llegan-reservas"],
  ["no me aparece una cita que se que existe", "tec-no-sale-cita"],
  ["busco a una clienta y no me sale su cita", "tec-no-sale-cita"],
  ["le doy a mandar whatsapp y no se abre", "tec-whatsapp-no-abre"],
  ["por que no se abre whatsapp al pulsar el boton", "tec-whatsapp-no-abre"],
  ["el panel va lentisimo, no se xq, que hago", "tec-panel-lento"],
  ["se me ha quedado colgada la pantalla", "tec-panel-lento"],
  ["no me llega el enlace para entrar, que hago", "tec-contrasena"],
  ["que tiempo hara mañana en madrid", "no-se"],
  ["cual es la capital de portugal", "no-se"],
  ["que pelicula me recomiendas para esta noche", "no-se"],
  ["cuanto es 235 x 12", "no-se"],
  ["como esta el trafico en la a3 ahora", "no-se"],
  ["cual es el proximo puente largo", "no-se"],
  ["sabes si va a llover estos dias", "no-se"],
  ["cual es la mejor epoca para viajar a japon", "no-se"],
  ["que receta rapida me haces para cenar", "no-se"],
  ["cuantos habitantes tiene madrid", "no-se"],
  ["que serie de netflix esta bien ahora", "no-se"],
  ["me recomiendas un libro para leer", "no-se"],
  ["quien gano el partido de anoche", "no-se"],
  ["que hora es en nueva york ahora mismo", "no-se"],
  ["como se dice gracias en italiano", "no-se"],
  ["que gimnasio me recomiendas cerca de aqui", "no-se"],
  ["cual es la mejor marca de lavadoras", "no-se"],
  ["que significa la palabra serendipia", "no-se"],
  ["cuanto cuesta un vuelo a canarias", "no-se"],
  ["sabes cuando es la proxima luna llena", "no-se"],
  ["que gastos se pueden desgravar como autonoma", "no-se"],
  ["sabes cual es el imc ideal", "no-se"],
  ["hay wifi gratis por aqui cerca", "no-se"],
  ["que serie me recomiendas de misterio", "no-se"],
  ["cuanto vale el iphone nuevo ahora", "no-se"],
];
