/**
 * Corpus CIEGO: 220 preguntas escritas por un agente aparte que solo vio los
 * ids y lo que responde cada intención, no el código, los ejemplos ni el
 * corpus de desarrollo (corpus.ts). Mide cómo generaliza el motor. No se
 * ajustan reglas mirando sus fallos: si se hace, deja de ser ciego.
 */
export const CORPUS_CIEGO: Array<[string, string]> = [
  ["cuantas citas hay hoy en total?", "citas-hoy"],
  ["cómo se reparten las citas de hoy entre todas", "citas-hoy"],
  ["cuantas citas tiene hoy Sara y cual es la siguiente", "citas-hoy-profesional"],
  ["Noelia cuantas le quedan hoy?", "citas-hoy-profesional"],
  ["quien esta ahora mismo en el sillon", "proxima-cita"],
  ["y despues de esta quien viene?", "proxima-cita"],
  ["pasame la lista de hoy por horas porfa", "lista-citas-hoy"],
  ["que queda hoy, todo por orden", "lista-citas-hoy"],
  ["cuantos huecos de media hora o mas quedan hoy?", "huecos-hoy"],
  ["cuanto tiempo libre me queda hoy y de quien", "huecos-hoy"],
  ["que % llevamos reservado hoy", "ocupacion-hoy"],
  ["como de llena esta el equipo oy?", "ocupacion-hoy"],
  ["cuanto vale el dia de hoy", "ingresos-hoy"],
  ["de lo de hoy cuanto llevo cobrado y cuanto falta?", "ingresos-hoy"],
  ["que tengo pendiente de mirar yo", "pendiente-de-ti"],
  ["hay algo esperandome, solicitudes o señales vencidas?", "pendiente-de-ti"],
  ["hay reservas de la web sin confirmar?", "solicitudes-pendientes"],
  ["cuantas solicitudes tengo por aceptar", "solicitudes-pendientes"],
  ["las citas de ayer, cuales no he marcado si vino o no", "por-marcar"],
  ["quedan citas pasadas sin marcar?", "por-marcar"],
  ["estamos abiertos ahora?", "abierto-ahora"],
  ["hasta que hora abrimos hoy", "abierto-ahora"],
  ["quien lleva color hoy y con que formula", "colores-hoy"],
  ["a alguna de hoy le falta anotar el tinte?", "colores-hoy"],
  ["que citas hay el martes", "citas-dia"],
  ["dime las citas del miercoles porfa", "citas-dia"],
  ["que tengo mñn por horas", "citas-manana"],
  ["como va la agenda de mañana?", "citas-manana"],
  ["huecos libres del jueves por profesional", "huecos-dia"],
  ["que huecos hay el lunes", "huecos-dia"],
  ["primer hueco libre para un tinte", "primer-hueco-servicio"],
  ["cuando hay sitio para mechas lo antes posible?", "primer-hueco-servicio"],
  ["cuando tiene hueco Maria esta semana", "hueco-profesional"],
  ["Sara cuando libra un rato la semana que viene?", "hueco-profesional"],
  ["cuantas citas llevamos esta semana comparado con la anterior", "citas-periodo"],
  ["citas de septiembre, cuantas van?", "citas-periodo"],
  ["ocupacion media del equipo este mes", "ocupacion-periodo"],
  ["como fue la ocupacion la semana pasada?", "ocupacion-periodo"],
  ["cuando viene {C} otra vez?", "proxima-cita-clienta"],
  ["{C} tiene cita pronto", "proxima-cita-clienta"],
  ["a quien tengo q avisar para mañana", "recordatorios-manana"],
  ["lista de recordatorios de mñn porfa", "recordatorios-manana"],
  ["quien esta en lista de espera?", "lista-espera"],
  ["para que servicio hay gente esperando hueco", "lista-espera"],
  ["que franja horaria es la mas floja ultimamente?", "franja-floja"],
  ["que dia suele ser el mas lleno de la semana", "dia-mas-lleno"],
  ["cuantas cancelaciones hubo esta semana?", "cancelaciones"],
  ["cancelaciones del mes pasado, cuantas fueron", "cancelaciones"],
  ["cuantos plantones llevamos y quien repite?", "plantones"],
  ["que se hizo {C} la ultima vez", "ultima-visita-clienta"],
  ["cuando vino {C} por ultima vez y con quien?", "ultima-visita-clienta"],
  ["cual es la ultima formula de {C}", "ultimo-color-clienta"],
  ["que color lleva anotado {C}?", "ultimo-color-clienta"],
  ["cada cuanto suele venir {C}", "frecuencia-clienta"],
  ["con que frecuencia viene {C} al salon?", "frecuencia-clienta"],
  ["cuanto se ha gastado {C} en total", "gasto-clienta"],
  ["que lleva gastado {C} aprox?", "gasto-clienta"],
  ["telefono de {C} porfa", "datos-clienta"],
  ["cuando es el cumple de {C}?", "datos-clienta"],
  ["hay alguna nota o aviso en la ficha de {C}?", "notas-clienta"],
  ["que observaciones tengo apuntadas de {C}", "notas-clienta"],
  ["cuantas clientas tengo en total en la cartera?", "clientas-total"],
  ["cuantas clientas nuevas vinieron este mes", "clientas-nuevas"],
  ["quien vino por primera vez la semana pasada?", "clientas-nuevas"],
  ["cuantas clientas repiten y que % es", "clientas-recurrentes"],
  ["que parte de la cartera es recurrente?", "clientas-recurrentes"],
  ["quien lleva tiempo sin aparecer por aqui", "clientas-inactivas"],
  ["cuantas clientas estan inactivas ya?", "clientas-inactivas"],
  ["quienes son las clientas que mas gastan", "mejores-clientas"],
  ["dame el top de clientas por gasto", "mejores-clientas"],
  ["clientas citadas en 15 dias sin color anotado, cuales son?", "color-pendiente"],
  ["quien cumple años este mes", "cumpleanos"],
  ["hay algun cumple en septiembre?", "cumpleanos"],
  ["quien tiene recargo pendiente?", "clientas-con-deuda"],
  ["cuanto suman las deudas de señales", "clientas-con-deuda"],
  ["{C} puede reservar por internet o la tengo bloqueada?", "clienta-bloqueada"],
  ["esta bloqueada {C} para reservar online", "clienta-bloqueada"],
  ["buscame la ficha de {C}", "buscar-clienta"],
  ["buscame a {C} por el apellido", "buscar-clienta"],
  ["horario semanal de Noelia", "horario-profesional"],
  ["que dias trabaja Sara?", "horario-profesional"],
  ["quien trabaja el martes", "quien-trabaja"],
  ["quien esta el lunes que viene?", "quien-trabaja"],
  ["cuantas citas ha hecho Maria este mes", "citas-profesional-periodo"],
  ["citas de Sara la semana pasada, cuantas fueron?", "citas-profesional-periodo"],
  ["ocupacion de Noelia esta semana", "ocupacion-profesional"],
  ["como anda de ocupada Maria este mes?", "ocupacion-profesional"],
  ["cuanto lleva cobrado Sara este mes", "dinero-profesional"],
  ["lo previsto de Noelia para esta semana?", "dinero-profesional"],
  ["que servicios hace mas Maria", "lo-que-mas-hace"],
  ["en que es en lo que mas trabaja Sara?", "lo-que-mas-hace"],
  ["con quien suele ir {C}", "profesional-habitual"],
  ["quien le hace normalmente el corte a {C}?", "profesional-habitual"],
  ["cuanto cuesta el tinte", "precio-servicio"],
  ["precio del peinado de novia?", "precio-servicio"],
  ["cuanto dura un recogido", "duracion-servicio"],
  ["cuanto tarda de verdad un tratamiento, no lo q dice la carta?", "duracion-servicio"],
  ["cual es el servicio mas pedido este mes", "servicio-mas-pedido"],
  ["que se pide mas en septiembre?", "servicio-mas-pedido"],
  ["que servicio deja mas por hora trabajada?", "servicio-mas-rentable"],
  ["que servicios tengo en la carta", "carta"],
  ["que se puede reservar desde la web?", "carta"],
  ["cuantas veces se ha hecho mechas este mes y cuanto ha dejado?", "veces-servicio"],
  ["cuanto llevo cobrado este mes", "cobrado-periodo"],
  ["lo cobrado la semana pasada cuanto fue?", "cobrado-periodo"],
  ["cuanto tengo previsto para la semana que viene", "previsto-periodo"],
  ["previsto de septiembre, cuanto va?", "previsto-periodo"],
  ["como va a acabar el mes, cobrado mas previsto", "estimacion-mes"],
  ["estimacion de cierre de septiembre?", "estimacion-mes"],
  ["cuanto entro por bizum este mes", "cobro-por-metodo"],
  ["cuanto se cobro en efectivo la semana pasada?", "cobro-por-metodo"],
  ["esta semana como va frente a la anterior", "comparar-periodos"],
  ["septiembre como compara con el mes pasado?", "comparar-periodos"],
  ["cual es el ticket medio de este mes", "precio-medio"],
  ["importe medio por cita la semana pasada?", "precio-medio"],
  ["cuanto ha dejado el tinte segun tarifa", "dinero-servicio"],
  ["lo que deja el recogido este mes?", "dinero-servicio"],
  ["pasame el resumen del mes en tres cifras", "resumen-mes"],
  ["como cierro el mes, dame las cifras clave?", "resumen-mes"],
  ["que señales estan pedidas y aun no han llegado?", "senales-pendientes"],
  ["cuantas señales tengo pendientes de cobrar", "senales-pendientes"],
  ["que señales se han pasado de plazo sin llegar?", "senales-vencidas"],
  ["la señal de la cita de {C} como va?", "senal-cita"],
  ["cuanto pido de señal y con que plazo?", "regla-senal"],
  ["señales recibidas esta semana, cuanto suman?", "senales-recibidas"],
  ["cuantas señales entraron en septiembre", "senales-recibidas"],
  ["que campaña me conviene lanzar ahora?", "campanas"],
  ["a cuanta gente le mandaria una campaña de tinte", "campanas"],
  ["cuantas clientas y huecos puedo recuperar este mes?", "recuperables"],
  ["que se puede recuperar todavia en septiembre", "recuperables"],
  ["la franja floja a quien se la ofrezco?", "huecos-flojos"],
  ["clientas nuevas que no han vuelto, cuales son?", "segunda-visita"],
  ["quien vino una vez y no ha repetido", "segunda-visita"],
  ["a quien le pido una reseña?", "resenas"],
  ["horario de apertura de toda la semana", "horario-salon"],
  ["a que hora abrimos los lunes y martes?", "horario-salon"],
  ["pasame el enlace de reservas para compartir", "enlace-reservas"],
  ["dame el link de reservas para poner en instagram?", "enlace-reservas"],
  ["que dice la web sobre cancelar una cita?", "politica-cancelacion"],
  ["que le preguntamos a la clienta al reservar?", "preguntas-reserva"],
  ["hay penalizacion si no vienen, cuanto es?", "plantones-config"],
  ["como son los mensajes de confirmacion que se mandan?", "mensajes-whatsapp"],
  ["la duracion se decide al aceptar cada solicitud?", "duracion-flexible"],
  ["las citas se ven en mi google calendar?", "calendario-suscrito"],
  ["puedo ver las citas desde el iphone, como lo activo?", "calendario-suscrito"],
  ["que color tiene cada profesional en el calendario?", "equipo-y-colores"],
  ["que categorias de preguntas hay, con ejemplos?", "que-puedo-preguntar"],
  ["que tipo de cosas te puedo preguntar, ponme ejemplos", "que-puedo-preguntar"],
  ["dame consejos para preguntar mejor", "como-preguntar"],
  ["tienes trucos para preguntarte mejor?", "como-preguntar"],
  ["buenos dias!", "saludo"],
  ["hola que tal", "saludo"],
  ["gracias majo", "gracias"],
  ["mil gracias tio", "gracias"],
  ["tu quien eres exactamente?", "quien-eres"],
  ["eres una ia o q", "quien-eres"],
  ["que puedes hacer tu?", "que-sabes-hacer"],
  ["para que sirves tu exactamente", "que-sabes-hacer"],
  ["me voy, hasta luego", "despedida"],
  ["me piro, nos vemos", "despedida"],
  ["buen curro el tuyo eh", "buen-trabajo"],
  ["que tal vas?", "como-estas"],
  ["no te he entendido bien, explicate", "no-entiendo"],
  ["necesito hablar con una persona de sishow", "ayuda-humana"],
  ["cuentame un chiste anda", "broma"],
  ["puedo meter mas de 3 profesionales?", "plan-mas-profesionales"],
  ["hasta cuantas profesionales me deja el plan", "plan-mas-profesionales"],
  ["puedo separar la carta por categorias en mi pagina?", "plan-segunda-pagina"],
  ["puedo tener mi propio dominio en vez del de sishow?", "plan-dominio-propio"],
  ["puedo descargarme el informe del mes?", "plan-informe-mensual"],
  ["los whatsapp se mandan solos?", "plan-whatsapp-automatico"],
  ["el mensaje de confirmacion sale automatico o lo mando yo?", "plan-whatsapp-automatico"],
  ["los recordatorios se mandan solos o uno a uno?", "plan-recordatorio-automatico"],
  ["puedo mandar todos los recordatorios de golpe", "plan-recordatorio-automatico"],
  ["puedo importar el excel de tpv123 cuando quiera?", "plan-importar-mensual"],
  ["el asistente viene incluido en el plan reservas? tb quiero saber si es plan aparte", "plan-asistente"],
  ["sishow me hace las facturas?", "no-hace-facturas"],
  ["puedo cobrar la señal con tarjeta?", "no-cobra-tarjeta"],
  ["si edito una cita se cambia tambien en mi google?", "no-escribe-google"],
  ["las campañas se mandan solas o las mando yo?", "no-campanas-automaticas"],
  ["como creo una cita nueva?", "tec-crear-cita"],
  ["donde le doy para meter una cita desde el movil", "tec-crear-cita"],
  ["como cambio la hora de una cita ya puesta?", "tec-mover-cita"],
  ["puedo mover una cita a otro dia, como", "tec-mover-cita"],
  ["como confirmo una cita de hoy?", "tec-confirmar"],
  ["donde le doy a confirmar cita", "tec-confirmar"],
  ["como cancelo una cita?", "tec-cancelar"],
  ["como rechazo una solicitud", "tec-cancelar"],
  ["donde anoto el color que le he puesto a una clienta?", "tec-anotar-color"],
  ["como importo el excel de tpv123?", "tec-importar-tpv"],
  ["por donde subo el excel de clientas", "tec-importar-tpv"],
  ["como pido la señal por whatsapp desde la cita?", "tec-senal"],
  ["donde cambio el horario de una profesional?", "tec-horario"],
  ["donde edito el precio de un servicio?", "tec-precios"],
  ["no me llegan reservas por la web, que reviso?", "tec-no-llegan-reservas"],
  ["no encuentro una cita en el calendario, que hago?", "tec-no-sale-cita"],
  ["el boton de whatsapp no me abre nada, xq?", "tec-whatsapp-no-abre"],
  ["el panel va lentisimo, que hago?", "tec-panel-lento"],
  ["no me llega el enlace para entrar, que hago?", "tec-contrasena"],
  ["como entro si no me acuerdo como acceder", "tec-contrasena"],
  ["que tiempo va a hacer mañana en madrid", "no-se"],
  ["dame una receta de lentejas facil", "no-se"],
  ["cuanto es 234 mas 587", "no-se"],
  ["quien gano el partido de anoche", "no-se"],
  ["que pelicula me recomiendas para esta noche", "no-se"],
  ["como se dice buenos dias en frances", "no-se"],
  ["cual es la capital de portugal", "no-se"],
  ["que carretera cojo para ir a valencia sin peajes", "no-se"],
  ["cuantos gramos tiene una taza de arroz", "no-se"],
  ["me puedes contar un poema corto", "no-se"],
  ["que dia cae la luna llena este mes", "no-se"],
  ["como quito una mancha de vino de la alfombra", "no-se"],
  ["que opinas del cambio climatico", "no-se"],
  ["cuanto cuesta un vuelo a canarias en septiembre", "no-se"],
  ["sabes hacer la o con un canuto", "no-se"],
  ["cual es la mejor epoca para plantar tomates", "no-se"],
  ["me recomiendas una serie para ver esta semana", "no-se"],
  ["cuanto pesa un elefante africano", "no-se"],
  ["que significa la palabra serendipia", "no-se"],
  ["como me quito el hipo rapido", "no-se"],
];
