/**
 * Tercer corpus CIEGO (ronda 7b): 250 preguntas de un agente nuevo que solo vio
 * el catálogo y la guía de uso. Medido una sola vez con el motor congelado en
 * 7217b26. No se ajusta nada mirando sus fallos.
 */
export const CORPUS_CIEGO_3: Array<[string, string]> = [
  ["cuantas citas tenemos hoy en total?", "citas-hoy"],
  ["¿cómo se reparten hoy las citas entre todas?", "citas-hoy"],
  ["cuantas citas tiene hoy Sara?", "citas-hoy-profesional"],
  ["q citas le quedan hoy a Noelia y cual es la siguiente?", "citas-hoy-profesional"],
  ["¿quién está ahora en cabina?", "proxima-cita"],
  ["quien viene despues de esta clienta?", "proxima-cita"],
  ["pasame la lista de citas de hoy por horas", "lista-citas-hoy"],
  ["q queda hoy, hora a hora?", "lista-citas-hoy"],
  ["cuantos huecos de media hora o mas quedan hoy?", "huecos-hoy"],
  ["¿q huecos libres tenemos hoy y de quién son?", "huecos-hoy"],
  ["¿qué % de la jornada tenemos ya reservado hoy?", "ocupacion-hoy"],
  ["como vamos de ocupacion hoy en general?", "ocupacion-hoy"],
  ["cuanto vale el dia de hoy?", "ingresos-hoy"],
  ["q llevamos cobrado hoy y q falta x cobrar?", "ingresos-hoy"],
  ["¿q tengo pendiente de revisar yo?", "pendiente-de-ti"],
  ["q me espera hoy a mi en el panel?", "pendiente-de-ti"],
  ["¿hay solicitudes de la web sin confirmar?", "solicitudes-pendientes"],
  ["cuantas reservas online estan esperando confirmacion?", "solicitudes-pendientes"],
  ["q citas de hoy faltan x marcar si vino o no?", "por-marcar"],
  ["¿tengo citas pasadas sin marcar todavia?", "por-marcar"],
  ["¿estamos abiertos ahora mismo?", "abierto-ahora"],
  ["hasta q hora abrimos hoy?", "abierto-ahora"],
  ["quien viene hoy a tinte y q formula lleva?", "colores-hoy"],
  ["¿hoy hay alguna con color sin formula apuntada?", "colores-hoy"],
  ["q citas hay el jueves?", "citas-dia"],
  ["dime las citas del lunes q viene", "citas-dia"],
  ["q tenemos mñn por horas?", "citas-manana"],
  ["¿pasame la agenda de mañana?", "citas-manana"],
  ["q huecos hay el martes x profesional?", "huecos-dia"],
  ["huecos libres del miercoles, quien los tiene?", "huecos-dia"],
  ["¿cuál es el primer hueco libre pa un corte?", "primer-hueco-servicio"],
  ["cuando hay primer hueco pa mechas?", "primer-hueco-servicio"],
  ["¿cuándo tiene hueco Maria esta semana?", "hueco-profesional"],
  ["q hueco tiene Sara la semana q viene?", "hueco-profesional"],
  ["cuantas citas llevamos este mes comparado con el anterior?", "citas-periodo"],
  ["¿q tal de citas esta semana frente a la pasada?", "citas-periodo"],
  ["¿cuál es la ocupacion media del equipo este mes?", "ocupacion-periodo"],
  ["como de ocupados hemos ido esta semana en general?", "ocupacion-periodo"],
  ["cuando viene {C} otra vez?", "proxima-cita-clienta"],
  ["¿{C} tiene cita esta semana?", "proxima-cita-clienta"],
  ["a quien tengo q mandar recordatorio de mañana?", "recordatorios-manana"],
  ["¿faltan recordatorios x enviar pa mañana?", "recordatorios-manana"],
  ["¿quién está en lista de espera?", "lista-espera"],
  ["q hay en la lista de espera y pa q servicio?", "lista-espera"],
  ["cual es la franja mas floja de las ultimas semanas?", "franja-floja"],
  ["¿q hora se queda mas vacia normalmente?", "franja-floja"],
  ["q dia fue el mas lleno este mes?", "dia-mas-lleno"],
  ["¿cuál es la hora con mas citas este mes?", "dia-mas-lleno"],
  ["cuantas citas se cancelaron este mes?", "cancelaciones"],
  ["¿cuántas cancelaciones hubo la semana pasada?", "cancelaciones"],
  ["cuantos plantones llevamos este mes?", "plantones"],
  ["¿quién repite en no presentarse?", "plantones"],
  ["q se hizo {C} la ultima vez?", "ultima-visita-clienta"],
  ["¿cuándo vino {C} x última vez y con quién?", "ultima-visita-clienta"],
  ["cual es la ultima formula de color de {C}?", "ultimo-color-clienta"],
  ["¿q color lleva apuntado {C}?", "ultimo-color-clienta"],
  ["cada cuanto suele venir {C}?", "frecuencia-clienta"],
  ["¿con q frecuencia viene {C} normalmente?", "frecuencia-clienta"],
  ["cuanto se ha gastado {C} en total?", "gasto-clienta"],
  ["¿q gasto lleva {C} aprox?", "gasto-clienta"],
  ["pasame el telefono de {C}", "datos-clienta"],
  ["¿cuál es el cumple de {C}?", "datos-clienta"],
  ["q notas tiene {C} en su ficha?", "notas-clienta"],
  ["¿hay algún aviso apuntado de {C}?", "notas-clienta"],
  ["cuantas clientas tenemos en total?", "clientas-total"],
  ["¿cuántas fichas de clientas llevamos?", "clientas-total"],
  ["cuantas clientas nuevas entraron este mes?", "clientas-nuevas"],
  ["¿quién vino x primera vez esta semana?", "clientas-nuevas"],
  ["q % de clientas son recurrentes?", "clientas-recurrentes"],
  ["¿cuántas clientas repiten normalmente?", "clientas-recurrentes"],
  ["cuantas clientas llevan mucho sin venir?", "clientas-inactivas"],
  ["¿quién lleva tiempo sin pisar el salón?", "clientas-inactivas"],
  ["quienes son las clientas q mas gastan?", "mejores-clientas"],
  ["dame el top de clientas x gasto", "mejores-clientas"],
  ["a quien le falta apuntar el color de las proximas 2 semanas?", "color-pendiente"],
  ["¿q clientas citadas pronto no tienen color anotado?", "color-pendiente"],
  ["quien cumple años este mes?", "cumpleanos"],
  ["¿hay algún cumple esta semana?", "cumpleanos"],
  ["quien tiene algun recargo pendiente?", "clientas-con-deuda"],
  ["¿cuánto suman las deudas de clientas ahora mismo?", "clientas-con-deuda"],
  ["{C} puede reservar x internet o esta bloqueada?", "clienta-bloqueada"],
  ["¿está bloqueada {C} pa reservar online?", "clienta-bloqueada"],
  ["buscame la ficha de {C}", "buscar-clienta"],
  ["abreme los datos de {C}", "buscar-clienta"],
  ["cual es el horario semanal de Noelia?", "horario-profesional"],
  ["¿q días trabaja Sara normalmente?", "horario-profesional"],
  ["quien trabaja el jueves?", "quien-trabaja"],
  ["¿quién viene a currar mañana?", "quien-trabaja"],
  ["cuantas citas ha echo Maria este mes?", "citas-profesional-periodo"],
  ["¿cuántas citas llevó Sara la semana pasada?", "citas-profesional-periodo"],
  ["como de ocupada va Noelia este mes?", "ocupacion-profesional"],
  ["¿q ocupación lleva Maria esta semana?", "ocupacion-profesional"],
  ["cuanto lleva cobrado Sara este mes?", "dinero-profesional"],
  ["¿q tiene previsto facturar Noelia esta semana?", "dinero-profesional"],
  ["q servicio hace mas Maria?", "lo-que-mas-hace"],
  ["¿en q se especializa mas Sara?", "lo-que-mas-hace"],
  ["con quien suele ir {C} normalmente?", "profesional-habitual"],
  ["¿quién atiende siempre a {C}?", "profesional-habitual"],
  ["cuanto cuesta un corte?", "precio-servicio"],
  ["¿q precio tiene el peinado de novia?", "precio-servicio"],
  ["cuanto dura un tinte normalmente?", "duracion-servicio"],
  ["¿q duración real tienen las mechas?", "duracion-servicio"],
  ["cual es el servicio mas pedido este mes?", "servicio-mas-pedido"],
  ["¿q se pide más, tinte o mechas, esta semana?", "servicio-mas-pedido"],
  ["q servicio deja mas x hora de curro?", "servicio-mas-rentable"],
  ["¿cuál es el más rentable de la carta?", "servicio-mas-rentable"],
  ["q servicios tenemos en la carta?", "carta"],
  ["¿q se puede reservar desde la página?", "carta"],
  ["cuantas veces se ha echo recogido este mes y cuanto dejo?", "veces-servicio"],
  ["¿cuántos tratamientos llevamos hechos en septiembre y cuánto han dejado?", "veces-servicio"],
  ["cuanto llevamos cobrado este mes?", "cobrado-periodo"],
  ["¿q se cobró la semana pasada?", "cobrado-periodo"],
  ["q tenemos previsto de aqui a fin de mes?", "previsto-periodo"],
  ["¿cuánto hay previsto pa la semana q viene?", "previsto-periodo"],
  ["como vamos a terminar el mes?", "estimacion-mes"],
  ["¿q estimación hay pa fin de mes?", "estimacion-mes"],
  ["cuanto entro x bizum este mes?", "cobro-por-metodo"],
  ["¿cómo se reparte lo cobrado entre efectivo y tarjeta?", "cobro-por-metodo"],
  ["como va este mes comparado con el anterior en general?", "comparar-periodos"],
  ["¿vamos mejor o peor q la semana pasada, en todo?", "comparar-periodos"],
  ["cual es el ticket medio de este mes?", "precio-medio"],
  ["¿cuánto sale de media cada cita esta semana?", "precio-medio"],
  ["cuanto ha dejado el tinte este mes segun tarifa?", "dinero-servicio"],
  ["¿q ha generado mechas en septiembre?", "dinero-servicio"],
  ["pasame el resumen del mes en excel", "resumen-mes"],
  ["dame el resumen rapido del mes en 3 cifras", "resumen-mes"],
  ["q señales estan pedidas y sin llegar?", "senales-pendientes"],
  ["¿hay señales pendientes de recibir ahora mismo?", "senales-pendientes"],
  ["q señales se pasaron de plazo sin pagar?", "senales-vencidas"],
  ["¿hay alguna señal vencida ahora?", "senales-vencidas"],
  ["{C} ya pago la señal de su cita?", "senal-cita"],
  ["¿cómo va la señal de {C}?", "senal-cita"],
  ["cuanto pedimos de señal y a quien?", "regla-senal"],
  ["¿q plazo damos pa pagar la señal?", "regla-senal"],
  ["cuantas señales entraron este mes y x cuanto?", "senales-recibidas"],
  ["¿q señales se recibieron la semana pasada?", "senales-recibidas"],
  ["q campaña me conviene lanzar ahora?", "campanas"],
  ["¿a cuánta gente le llegaría una campaña de cumpleaños?", "campanas"],
  ["cuantas clientas se pueden recuperar este mes?", "recuperables"],
  ["¿cuántos huecos se pueden aún rellenar este mes?", "recuperables"],
  ["a quien le ofrezco los huecos de la franja floja?", "huecos-flojos"],
  ["¿q franja floja tengo y a quién se la mando?", "huecos-flojos"],
  ["q clientas nuevas no han vuelto todavia?", "segunda-visita"],
  ["¿quién vino una vez y no repitió?", "segunda-visita"],
  ["a quien le pido una reseña?", "resenas"],
  ["¿quién sería buena candidata pa pedirle reseña?", "resenas"],
  ["cual es el horario del salon esta semana?", "horario-salon"],
  ["¿q horario tenemos de apertura?", "horario-salon"],
  ["pasame el enlace de reservas pa compartir", "enlace-reservas"],
  ["dame el link de la pagina de reservas", "enlace-reservas"],
  ["q pone la web sobre cancelaciones?", "politica-cancelacion"],
  ["¿q política de cancelación tenemos publicada?", "politica-cancelacion"],
  ["q le preguntamos a la clienta al reservar?", "preguntas-reserva"],
  ["¿q datos pedimos en el formulario de reserva?", "preguntas-reserva"],
  ["tenemos penalizacion x no presentarse?", "plantones-config"],
  ["¿cuánto se cobra si hay plantón?", "plantones-config"],
  ["como es el mensaje de confirmacion q se manda?", "mensajes-whatsapp"],
  ["¿q texto lleva el recordatorio de whatsapp?", "mensajes-whatsapp"],
  ["la duracion se decide al aceptar cada solicitud?", "duracion-flexible"],
  ["¿puedo ajustar la duración al confirmar la cita?", "duracion-flexible"],
  ["puedo ver las citas en mi google calendar?", "calendario-suscrito"],
  ["¿cómo activo ver las citas en el iphone?", "calendario-suscrito"],
  ["q color tiene cada servicio en el calendario?", "equipo-y-colores"],
  ["¿de q color sale Sara en el calendario?", "equipo-y-colores"],
  ["q tipo de cosas te puedo preguntar?", "que-puedo-preguntar"],
  ["dame ejemplos de preguntas q te puedo hacer", "que-puedo-preguntar"],
  ["como te tengo q preguntar pa q me entiendas mejor?", "como-preguntar"],
  ["¿algún consejo pa preguntarte bien?", "como-preguntar"],
  ["holaa", "saludo"],
  ["buenos dias! q tal", "saludo"],
  ["gracias wapa", "gracias"],
  ["tu q eres exactamente?", "quien-eres"],
  ["¿eres una ia o q?", "quien-eres"],
  ["q cosas sabes hacer tu?", "que-sabes-hacer"],
  ["¿pa q me sirves exactamente?", "que-sabes-hacer"],
  ["bueno me voy, hasta luego", "despedida"],
  ["q bien lo estas haciendo, macho", "buen-trabajo"],
  ["q tal estas hoy?", "como-estas"],
  ["¿todo bien x ahí?", "como-estas"],
  ["eeh no se ni q preguntarte la verdad jaja", "no-entiendo"],
  ["pspsps oye tu", "no-entiendo"],
  ["quiero hablar con una persona d soporte", "ayuda-humana"],
  ["cuentame un chiste anda", "broma"],
  ["puedo meter mas de 3 profesionales en mi plan?", "plan-mas-profesionales"],
  ["¿hasta cuántas profesionales me deja añadir esto?", "plan-mas-profesionales"],
  ["la carta se puede separar x categorias?", "plan-segunda-pagina"],
  ["puedo tener un dominio propio pa la reserva o q?", "plan-dominio-propio"],
  ["¿puedo descargarme un informe mensual?", "plan-informe-mensual"],
  ["las confirmaciones de whatsapp se mandan solas o las envio yo?", "plan-whatsapp-automatico"],
  ["los recordatorios de mañana se mandan automaticos o los doy yo uno x uno?", "plan-recordatorio-automatico"],
  ["puedo importar el excel del tpv cuando quiera o solo una vez?", "plan-importar-mensual"],
  ["el asistente viene incluido en mi plan?", "plan-asistente"],
  ["¿tengo el chat del asistente activo o hay q pagar aparte?", "plan-asistente"],
  ["puedo sacar facturas desde aqui?", "no-hace-facturas"],
  ["se puede cobrar la señal con tarjeta?", "no-cobra-tarjeta"],
  ["si cambio algo en mi google calendar se actualiza aqui tmb?", "no-escribe-google"],
  ["las campañas de marketing se mandan solas sin q yo haga nada?", "no-campanas-automaticas"],
  ["¿las señas se pueden cobrar en efectivo en mano?", "no-cobra-tarjeta"],
  ["como creo una cita nueva?", "tec-crear-cita"],
  ["donde le doy pa meter una cita?", "tec-crear-cita"],
  ["como cambio la hora de una cita ya puesta?", "tec-mover-cita"],
  ["¿cómo muevo una cita a otro día?", "tec-mover-cita"],
  ["como confirmo una solicitud q ha entrado?", "tec-confirmar"],
  ["¿dónde acepto las peticiones de la web?", "tec-confirmar"],
  ["como anulo una cita?", "tec-cancelar"],
  ["¿cómo rechazo una solicitud q no me cabe?", "tec-cancelar"],
  ["como apunto el color de una clienta?", "tec-anotar-color"],
  ["¿dónde meto la fórmula de tinte en la ficha?", "tec-anotar-color"],
  ["como importo las clientas del tpv?", "tec-importar-tpv"],
  ["¿de dónde subo el excel de clientas?", "tec-importar-tpv"],
  ["como pido la señal x whatsapp a una clienta?", "tec-senal"],
  ["¿dónde configuro cuánta señal pedir?", "tec-senal"],
  ["donde cambio el horario del salon?", "tec-horario"],
  ["¿cómo edito el horario de una profesional?", "tec-horario"],
  ["como cambio el precio de un servicio?", "tec-precios"],
  ["¿dónde añado un servicio nuevo?", "tec-precios"],
  ["xq no me llegan reservas de la web?", "tec-no-llegan-reservas"],
  ["no entra ninguna reserva online, q reviso?", "tec-no-llegan-reservas"],
  ["no encuentro una cita q se q existe, q hago?", "tec-no-sale-cita"],
  ["¿no me sale una cita en el calendario, xq será?", "tec-no-sale-cita"],
  ["xq no me abre whatsapp al querer escribir a una clienta?", "tec-whatsapp-no-abre"],
  ["no me deja mandar whatsapp desde la ficha, q fallo es?", "tec-whatsapp-no-abre"],
  ["el panel va muy lento, q hago?", "tec-panel-lento"],
  ["¿se queda pillado esto, cómo lo arreglo?", "tec-panel-lento"],
  ["no me llega el enlace pa entrar, q hago?", "tec-contrasena"],
  ["q tiempo va a hacer mañana?", "no-se"],
  ["¿sabes si llueve esta semana?", "no-se"],
  ["cuanto cuesta un iphone 17 ahora?", "no-se"],
  ["receta rapida de tortilla de patatas?", "no-se"],
  ["¿a q hora juega el madrid hoy?", "no-se"],
  ["como saco cita pa la dgt?", "no-se"],
  ["sabes algo de la renta de este año?", "no-se"],
  ["q pelicula ponen esta noche?", "no-se"],
  ["¿cuánto tarda en llegar un paquete de amazon?", "no-se"],
  ["como se hace una paella buena?", "no-se"],
  ["necesito comprarme una lavadora nueva, alguna recomendacion?", "no-se"],
  ["como reseteo mi router de casa?", "no-se"],
  ["¿sabes cuándo es el black friday este año?", "no-se"],
  ["cual es la capital de portugal?", "no-se"],
  ["como renuevo el dni?", "no-se"],
  ["¿qué tal está el ibex hoy?", "no-se"],
  ["me recomiendas una serie pa ver esta noche?", "no-se"],
  ["cuanto es 15% de 340?", "no-se"],
  ["como quito una mancha de vino de la alfombra?", "no-se"],
  ["¿sabes si mañana hay huelga de trenes?", "no-se"],
  ["cual fue el resultado del barça anoche?", "no-se"],
  ["como pongo el wifi de casa mas rapido?", "no-se"],
  ["¿sabes alguna app buena pa hacer dieta?", "no-se"],
  ["cuanto necesito ahorrar pa la jubilacion?", "no-se"],
  ["mi hijo tiene examen mñn, sabes algun truco pa estudiar rapido?", "no-se"],
];
