/**
 * Corpus de evaluación del asistente: formulaciones NUEVAS (no las de la
 * especificación) con la intención esperada. Marcadores que el test rellena
 * con datos reales de la demo PeluChic:
 *   {C} nombre completo de una clienta única · {P} una profesional ·
 *   {S} un servicio de la carta.
 * «no-se» = fuera del dominio: debe decir que no lo sabe.
 */
export const CORPUS: Array<[string, string]> = [
  // ── Hoy ──────────────────────────────────────────────────────────────
  ["cuantas citas hay para hoy", "citas-hoy"],
  ["cuántas clientas tenemos hoy?", "citas-hoy"],
  ["numero de citas de hoy", "citas-hoy"],
  ["hoy cuanta gente tenemos", "citas-hoy"],
  ["oy cuantas citas", "citas-hoy"],
  ["cuantas citas tiene {P} hoy", "citas-hoy-profesional"],
  ["{P} cuantas tiene hoy", "citas-hoy-profesional"],
  ["citas de {P} para hoy", "citas-hoy-profesional"],
  ["que tiene hoy {P}", "citas-hoy-profesional"],
  ["hoy {P} cuantas clientas", "citas-hoy-profesional"],
  ["quien es la siguiente", "proxima-cita"],
  ["quien viene ahora", "proxima-cita"],
  ["cual es la proxima cita", "proxima-cita"],
  ["quien esta ahora en el salon", "proxima-cita"],
  ["a quien le toca ahora", "proxima-cita"],
  ["que citas me quedan hoy", "lista-citas-hoy"],
  ["lista de las citas de hoy", "lista-citas-hoy"],
  ["dime las citas que quedan", "lista-citas-hoy"],
  ["quienes vienen hoy", "lista-citas-hoy"],
  ["que me queda por hoy", "lista-citas-hoy"],
  ["hay algun hueco hoy", "huecos-hoy"],
  ["huecos libres para hoy", "huecos-hoy"],
  ["queda sitio hoy", "huecos-hoy"],
  ["tengo algo libre esta tarde", "huecos-hoy"],
  ["hueco hoy para alguien", "huecos-hoy"],
  ["como de llena esta la agenda hoy", "ocupacion-hoy"],
  ["ocupacion de hoy", "ocupacion-hoy"],
  ["que porcentaje llevamos hoy ocupado", "ocupacion-hoy"],
  ["estamos llenos hoy", "ocupacion-hoy"],
  ["cuanto hemos sacado hoy", "ingresos-hoy"],
  ["caja de hoy", "ingresos-hoy"],
  ["cuanto llevo cobrado hoy", "ingresos-hoy"],
  ["que dinero llevamos hoy", "ingresos-hoy"],
  ["cuanto voy a sacar hoy", "ingresos-hoy"],
  ["que tengo pendiente", "pendiente-de-ti"],
  ["que me falta por hacer", "pendiente-de-ti"],
  ["tengo algo pendiente", "pendiente-de-ti"],
  ["que cosas tengo por resolver", "pendiente-de-ti"],
  ["hay solicitudes nuevas", "solicitudes-pendientes"],
  ["reservas por confirmar", "solicitudes-pendientes"],
  ["cuantas solicitudes tengo sin aceptar", "solicitudes-pendientes"],
  ["alguna peticion de cita nueva", "solicitudes-pendientes"],
  ["que citas me faltan por marcar", "por-marcar"],
  ["citas sin marcar", "por-marcar"],
  ["me falta marcar si vinieron", "por-marcar"],
  ["cuantas tengo sin cerrar", "por-marcar"],
  ["estamos abiertos", "abierto-ahora"],
  ["abrimos hoy", "abierto-ahora"],
  ["hasta que hora abrimos hoy", "abierto-ahora"],
  ["esta abierto el salon ahora", "abierto-ahora"],
  ["que colores hay hoy", "colores-hoy"],
  ["tintes de hoy y sus formulas", "colores-hoy"],
  ["que formulas necesito hoy", "colores-hoy"],
  ["colores para hoy", "colores-hoy"],

  // ── Agenda ───────────────────────────────────────────────────────────
  ["cuantas citas hay el martes", "citas-dia"],
  ["que tengo el jueves", "citas-dia"],
  ["citas del miercoles", "citas-dia"],
  ["quien viene el lunes", "citas-dia"],
  ["agenda del 3 de octubre", "citas-dia"],
  ["cuantas citas tengo mañana", "citas-manana"],
  ["que hay mañana", "citas-manana"],
  ["citas para mañana", "citas-manana"],
  ["quien viene mañana", "citas-manana"],
  ["mñn cuantas", "citas-manana"],
  ["huecos el martes", "huecos-dia"],
  ["hay sitio el jueves", "huecos-dia"],
  ["que huecos quedan el miercoles", "huecos-dia"],
  ["tengo algo libre el martes por la tarde", "huecos-dia"],
  ["cuando puedo meter {S}", "primer-hueco-servicio"],
  ["primer hueco para {S}", "primer-hueco-servicio"],
  ["cuando hay sitio para {S}", "primer-hueco-servicio"],
  ["donde cabe {S}", "primer-hueco-servicio"],
  ["cuando tiene hueco {P}", "hueco-profesional"],
  ["primer hueco de {P}", "hueco-profesional"],
  ["{P} cuando esta libre", "hueco-profesional"],
  ["cuando puede {P}", "hueco-profesional"],
  ["cuantas citas esta semana", "citas-periodo"],
  ["citas de este mes", "citas-periodo"],
  ["cuantas citas la semana que viene", "citas-periodo"],
  ["cuantas citas hubo la semana pasada", "citas-periodo"],
  ["numero de citas en septiembre", "citas-periodo"],
  ["ocupacion de esta semana", "ocupacion-periodo"],
  ["como de llenos vamos este mes", "ocupacion-periodo"],
  ["porcentaje de ocupacion del mes", "ocupacion-periodo"],
  ["ocupacion la semana pasada", "ocupacion-periodo"],
  ["cuando viene {C}", "proxima-cita-clienta"],
  ["proxima cita de {C}", "proxima-cita-clienta"],
  ["{C} tiene cita", "proxima-cita-clienta"],
  ["cuando le toca a {C}", "proxima-cita-clienta"],
  ["recordatorios de mañana", "recordatorios-manana"],
  ["a quien tengo que recordar para mañana", "recordatorios-manana"],
  ["he mandado los recordatorios", "recordatorios-manana"],
  ["faltan recordatorios", "recordatorios-manana"],
  ["quien esta en lista de espera", "lista-espera"],
  ["lista de espera", "lista-espera"],
  ["hay gente esperando hueco", "lista-espera"],
  ["quien espera para {S}", "lista-espera"],
  ["cual es la franja mas floja", "franja-floja"],
  ["que hora va peor", "franja-floja"],
  ["cuando tenemos menos gente", "franja-floja"],
  ["que dia flojea mas", "franja-floja"],
  ["que dia hay mas citas", "dia-mas-lleno"],
  ["dia mas lleno de la semana", "dia-mas-lleno"],
  ["cual es el dia con mas trabajo", "dia-mas-lleno"],
  ["que dia vamos mas cargadas", "dia-mas-lleno"],
  ["cuantas cancelaciones hay", "cancelaciones"],
  ["cuantas han cancelado esta semana", "cancelaciones"],
  ["cancelaciones del mes", "cancelaciones"],
  ["quien ha anulado", "cancelaciones"],
  ["cuantos plantones", "plantones"],
  ["quien no vino este mes", "plantones"],
  ["cuantas no se presentaron", "plantones"],
  ["quien me ha dado plantón", "plantones"],
  ["cuantas faltaron la semana pasada", "plantones"],

  // ── Clientas ─────────────────────────────────────────────────────────
  ["cuando vino por ultima vez {C}", "ultima-visita-clienta"],
  ["ultima visita de {C}", "ultima-visita-clienta"],
  ["cuanto hace que no viene {C}", "ultima-visita-clienta"],
  ["que se hizo {C} la ultima vez", "ultima-visita-clienta"],
  ["que color lleva {C}", "ultimo-color-clienta"],
  ["formula de {C}", "ultimo-color-clienta"],
  ["que tinte le pusimos a {C}", "ultimo-color-clienta"],
  ["el color de {C}", "ultimo-color-clienta"],
  ["cada cuanto viene {C}", "frecuencia-clienta"],
  ["cada cuantas semanas viene {C}", "frecuencia-clienta"],
  ["con que frecuencia viene {C}", "frecuencia-clienta"],
  ["{C} cada cuanto viene", "frecuencia-clienta"],
  ["cuanto se ha gastado {C}", "gasto-clienta"],
  ["cuanto lleva gastado {C}", "gasto-clienta"],
  ["cuanto dinero nos ha dejado {C}", "gasto-clienta"],
  ["gasto de {C}", "gasto-clienta"],
  ["telefono de {C}", "datos-clienta"],
  ["dame el movil de {C}", "datos-clienta"],
  ["como contacto con {C}", "datos-clienta"],
  ["el email de {C}", "datos-clienta"],
  ["que notas tengo de {C}", "notas-clienta"],
  ["que tengo apuntado de {C}", "notas-clienta"],
  ["observaciones de {C}", "notas-clienta"],
  ["algo que saber de {C}", "notas-clienta"],
  ["cuantas clientas tengo", "clientas-total"],
  ["cuantas clientas hay en total", "clientas-total"],
  ["numero de clientas", "clientas-total"],
  ["tamaño de mi cartera", "clientas-total"],
  ["clientas nuevas este mes", "clientas-nuevas"],
  ["cuantas nuevas han venido", "clientas-nuevas"],
  ["gente nueva esta semana", "clientas-nuevas"],
  ["cuantas vienen por primera vez", "clientas-nuevas"],
  ["cuantas clientas repiten", "clientas-recurrentes"],
  ["clientas fieles", "clientas-recurrentes"],
  ["cuantas vuelven", "clientas-recurrentes"],
  ["porcentaje de clientas que repiten", "clientas-recurrentes"],
  ["quien lleva tiempo sin venir", "clientas-inactivas"],
  ["clientas que no vuelven", "clientas-inactivas"],
  ["quien hace mucho que no viene", "clientas-inactivas"],
  ["clientas perdidas", "clientas-inactivas"],
  ["quienes son las que mas gastan", "mejores-clientas"],
  ["mejores clientas", "mejores-clientas"],
  ["top clientas", "mejores-clientas"],
  ["quien me deja mas dinero", "mejores-clientas"],
  ["a quien le falta el color apuntado", "color-pendiente"],
  ["colores sin anotar", "color-pendiente"],
  ["que formulas me faltan", "color-pendiente"],
  ["color pendiente", "color-pendiente"],
  ["quien cumple años", "cumpleanos"],
  ["cumpleaños esta semana", "cumpleanos"],
  ["alguna clienta cumple este mes", "cumpleanos"],
  ["hay algun cumple", "cumpleanos"],
  ["quien me debe dinero", "clientas-con-deuda"],
  ["clientas con deuda", "clientas-con-deuda"],
  ["hay alguien que deba algo", "clientas-con-deuda"],
  ["deudas pendientes", "clientas-con-deuda"],
  ["puede reservar {C}", "clienta-bloqueada"],
  ["{C} esta bloqueada", "clienta-bloqueada"],
  ["por que {C} no puede reservar", "clienta-bloqueada"],
  ["tiene bloqueo {C}", "clienta-bloqueada"],
  ["busca a {C}", "buscar-clienta"],
  ["quien es {C}", "buscar-clienta"],
  ["ficha de {C}", "buscar-clienta"],
  ["{C}", "buscar-clienta"],

  // ── Equipo ───────────────────────────────────────────────────────────
  ["que horario tiene {P}", "horario-profesional"],
  ["cuando trabaja {P}", "horario-profesional"],
  ["horario de {P}", "horario-profesional"],
  ["a que hora entra {P}", "horario-profesional"],
  ["quien trabaja el sabado", "quien-trabaja"],
  ["quien viene a trabajar mañana", "quien-trabaja"],
  ["quien esta hoy en el salon trabajando", "quien-trabaja"],
  ["quienes trabajan el martes", "quien-trabaja"],
  ["cuantas citas lleva {P} este mes", "citas-profesional-periodo"],
  ["citas de {P} esta semana", "citas-profesional-periodo"],
  ["como va {P}", "citas-profesional-periodo"],
  ["cuantas clientas ha atendido {P} este mes", "citas-profesional-periodo"],
  ["ocupacion de {P}", "ocupacion-profesional"],
  ["como de llena va {P}", "ocupacion-profesional"],
  ["{P} esta muy cargada", "ocupacion-profesional"],
  ["porcentaje ocupado de {P}", "ocupacion-profesional"],
  ["cuanto ha facturado {P}", "dinero-profesional"],
  ["dinero de {P} este mes", "dinero-profesional"],
  ["cuanto lleva cobrado {P}", "dinero-profesional"],
  ["cuanto saca {P}", "dinero-profesional"],
  ["que es lo que mas hace {P}", "lo-que-mas-hace"],
  ["que servicios hace mas {P}", "lo-que-mas-hace"],
  ["en que se especializa {P}", "lo-que-mas-hace"],
  ["lo que mas le piden a {P}", "lo-que-mas-hace"],
  ["con quien va {C}", "profesional-habitual"],
  ["quien atiende a {C}", "profesional-habitual"],
  ["{C} con quien suele ir", "profesional-habitual"],
  ["quien le hace el pelo a {C}", "profesional-habitual"],

  // ── Servicios ────────────────────────────────────────────────────────
  ["cuanto cuesta {S}", "precio-servicio"],
  ["precio de {S}", "precio-servicio"],
  ["a cuanto esta {S}", "precio-servicio"],
  ["cuanto cobramos por {S}", "precio-servicio"],
  ["cuanto dura {S}", "duracion-servicio"],
  ["duracion de {S}", "duracion-servicio"],
  ["cuanto tiempo lleva {S}", "duracion-servicio"],
  ["{S} cuanto tarda", "duracion-servicio"],
  ["que es lo mas pedido", "servicio-mas-pedido"],
  ["servicio estrella", "servicio-mas-pedido"],
  ["que servicio se hace mas", "servicio-mas-pedido"],
  ["que piden mas las clientas", "servicio-mas-pedido"],
  ["que servicio deja mas por hora", "servicio-mas-rentable"],
  ["cual es el servicio mas rentable", "servicio-mas-rentable"],
  ["que me sale mas a cuenta", "servicio-mas-rentable"],
  ["servicio que mas renta", "servicio-mas-rentable"],
  ["que servicios tengo", "carta"],
  ["carta de servicios", "carta"],
  ["lista de precios", "carta"],
  ["que ofrecemos", "carta"],
  ["cuantas veces he hecho {S} este mes", "veces-servicio"],
  ["cuantos {S} llevamos", "veces-servicio"],
  ["numero de {S} esta semana", "veces-servicio"],
  ["cuantas veces se ha pedido {S}", "veces-servicio"],

  // ── Dinero ───────────────────────────────────────────────────────────
  ["cuanto he cobrado este mes", "cobrado-periodo"],
  ["facturacion de la semana", "cobrado-periodo"],
  ["cuanto hemos ganado este mes", "cobrado-periodo"],
  ["caja del mes pasado", "cobrado-periodo"],
  ["cuanto sacamos la semana pasada", "cobrado-periodo"],
  ["cuanto tengo previsto la semana que viene", "previsto-periodo"],
  ["que dinero entra la proxima semana", "previsto-periodo"],
  ["previsto para lo que queda de mes", "previsto-periodo"],
  ["cuanto voy a cobrar la semana que viene", "previsto-periodo"],
  ["cuanto voy a hacer este mes", "estimacion-mes"],
  ["estimacion del mes", "estimacion-mes"],
  ["como cerraremos el mes", "estimacion-mes"],
  ["a cuanto llegaremos este mes", "estimacion-mes"],
  ["cuanto en tarjeta y cuanto en efectivo", "cobro-por-metodo"],
  ["cobros por bizum", "cobro-por-metodo"],
  ["cuanto efectivo hay hoy", "cobro-por-metodo"],
  ["desglose por forma de pago", "cobro-por-metodo"],
  ["como va el mes comparado con el anterior", "comparar-periodos"],
  ["comparado con el mes pasado", "comparar-periodos"],
  ["vamos mejor que el mes pasado", "comparar-periodos"],
  ["comparar esta semana con la pasada", "comparar-periodos"],
  ["cuanto deja cada cita de media", "precio-medio"],
  ["ticket medio", "precio-medio"],
  ["precio medio por cita", "precio-medio"],
  ["media de dinero por clienta", "precio-medio"],
  ["cuanto han dejado {S} este mes", "dinero-servicio"],
  ["dinero de {S}", "dinero-servicio"],
  ["cuanto facturamos en {S}", "dinero-servicio"],
  ["cuanto sacamos con {S}", "dinero-servicio"],
  ["que tal va el mes", "resumen-mes"],
  ["resumen del mes", "resumen-mes"],
  ["como vamos este mes", "resumen-mes"],
  ["balance del mes", "resumen-mes"],

  // ── Señal ────────────────────────────────────────────────────────────
  ["que señales estoy esperando", "senales-pendientes"],
  ["señales pendientes", "senales-pendientes"],
  ["quien tiene que pagar la señal", "senales-pendientes"],
  ["bizums pendientes", "senales-pendientes"],
  ["hay señales vencidas", "senales-vencidas"],
  ["señales caducadas", "senales-vencidas"],
  ["a quien se le paso el plazo de la señal", "senales-vencidas"],
  ["señales fuera de plazo", "senales-vencidas"],
  ["ha pagado la señal {C}", "senal-cita"],
  ["señal de {C}", "senal-cita"],
  ["{C} ha hecho el bizum", "senal-cita"],
  ["esta pagada la señal de {C}", "senal-cita"],
  ["cuanto pido de señal", "regla-senal"],
  ["como tengo configurada la señal", "regla-senal"],
  ["a quien pido señal", "regla-senal"],
  ["regla de la señal", "regla-senal"],
  ["cuantas señales he recibido", "senales-recibidas"],
  ["señales cobradas este mes", "senales-recibidas"],
  ["dinero de señales recibido", "senales-recibidas"],
  ["cuantos bizums me han llegado", "senales-recibidas"],

  // ── Marketing ────────────────────────────────────────────────────────
  ["que campaña me conviene", "campanas"],
  ["que campañas hay", "campanas"],
  ["ideas de marketing", "campanas"],
  ["que puedo mandar a las clientas", "campanas"],
  ["cuantas clientas puedo recuperar", "recuperables"],
  ["cuanto puedo recuperar este mes", "recuperables"],
  ["clientas recuperables", "recuperables"],
  ["a cuantas puedo volver a traer", "recuperables"],
  ["como lleno los huecos flojos", "huecos-flojos"],
  ["llenar los martes por la tarde", "huecos-flojos"],
  ["ofrecer huecos flojos", "huecos-flojos"],
  ["como relleno las horas malas", "huecos-flojos"],
  ["quien vino una vez y no volvio", "segunda-visita"],
  ["clientas de una sola visita", "segunda-visita"],
  ["segunda visita", "segunda-visita"],
  ["nuevas que no han repetido", "segunda-visita"],
  ["a quien pido reseña", "resenas"],
  ["reseñas de google", "resenas"],
  ["pedir opiniones a las clientas", "resenas"],
  ["quien me puede dejar una reseña", "resenas"],

  // ── Configuración ────────────────────────────────────────────────────
  ["que horario tiene el salon", "horario-salon"],
  ["horario de la peluqueria", "horario-salon"],
  ["a que hora abrimos", "horario-salon"],
  ["que dias abrimos", "horario-salon"],
  ["cual es mi enlace de reservas", "enlace-reservas"],
  ["pasame el link de la web", "enlace-reservas"],
  ["url de mi pagina", "enlace-reservas"],
  ["donde reservan las clientas", "enlace-reservas"],
  ["que dice mi web de cancelar", "politica-cancelacion"],
  ["politica de cancelacion", "politica-cancelacion"],
  ["pueden cancelar gratis", "politica-cancelacion"],
  ["con cuanta antelacion pueden anular", "politica-cancelacion"],
  ["que pregunto al reservar", "preguntas-reserva"],
  ["preguntas del formulario de reserva", "preguntas-reserva"],
  ["que les pido cuando reservan", "preguntas-reserva"],
  ["preguntas de la reserva", "preguntas-reserva"],
  ["cobro algo si no vienen", "plantones-config"],
  ["tengo penalizacion por plantón", "plantones-config"],
  ["recargo por no venir", "plantones-config"],
  ["que pasa si no se presentan", "plantones-config"],
  ["que dice el recordatorio", "mensajes-whatsapp"],
  ["mensaje de whatsapp de confirmacion", "mensajes-whatsapp"],
  ["texto del recordatorio de whatsapp", "mensajes-whatsapp"],
  ["que les mando por whatsapp", "mensajes-whatsapp"],
  ["fijo yo la duracion", "duracion-flexible"],
  ["duracion flexible", "duracion-flexible"],
  ["quien decide cuanto dura la cita", "duracion-flexible"],
  ["la duracion la pongo al confirmar", "duracion-flexible"],
  ["puedo ver las citas en google calendar", "calendario-suscrito"],
  ["sincronizar con el calendario del movil", "calendario-suscrito"],
  ["ver la agenda en el iphone", "calendario-suscrito"],
  ["calendario de google", "calendario-suscrito"],
  ["de que color sale cada una", "equipo-y-colores"],
  ["colores del calendario", "equipo-y-colores"],
  ["que color es {P} en la agenda", "equipo-y-colores"],
  ["color de cada servicio", "equipo-y-colores"],

  // ── Ayuda ────────────────────────────────────────────────────────────
  ["que te puedo preguntar", "que-puedo-preguntar"],
  ["que preguntas entiendes", "que-puedo-preguntar"],
  ["dame ejemplos de preguntas", "que-puedo-preguntar"],
  ["como te pregunto", "como-preguntar"],
  ["como tengo que escribirte", "como-preguntar"],
  ["como te hablo para que me entiendas", "como-preguntar"],

  // ── Charla ───────────────────────────────────────────────────────────
  ["hola!", "saludo"],
  ["buenos dias", "saludo"],
  ["buenas tardes", "saludo"],
  ["muchas gracias", "gracias"],
  ["gracias!!", "gracias"],
  ["quien eres", "quien-eres"],
  ["eres una ia?", "quien-eres"],
  ["que sabes hacer", "que-sabes-hacer"],
  ["para que sirves", "que-sabes-hacer"],
  ["adios", "despedida"],
  ["hasta mañana", "despedida"],
  ["muy bien hecho", "buen-trabajo"],
  ["eres un crack", "buen-trabajo"],
  ["que tal estas", "como-estas"],
  ["como estas hoy", "como-estas"],
  ["no te entiendo", "no-entiendo"],
  ["no me has entendido", "no-entiendo"],
  ["quiero hablar con una persona", "ayuda-humana"],
  ["necesito ayuda de alguien", "ayuda-humana"],
  ["cuentame un chiste", "broma"],
  ["dime algo gracioso", "broma"],

  // ── Fuera de plan ────────────────────────────────────────────────────
  ["quiero meter a otra peluquera en el equipo", "plan-mas-profesionales"],
  ["podemos ser cinco en el equipo", "plan-mas-profesionales"],
  ["quiero otra web para novias", "plan-segunda-pagina"],
  ["puedo tener una segunda pagina", "plan-segunda-pagina"],
  ["quiero mi dominio propio", "plan-dominio-propio"],
  ["usar peluchic.es para reservar", "plan-dominio-propio"],
  ["mandame un informe cada mes", "plan-informe-mensual"],
  ["resumen mensual por correo", "plan-informe-mensual"],
  ["que whatsapp conteste solo", "plan-whatsapp-automatico"],
  ["respuestas automaticas de whatsapp", "plan-whatsapp-automatico"],
  ["recordatorios automaticos", "plan-recordatorio-automatico"],
  ["que se manden solos los recordatorios", "plan-recordatorio-automatico"],
  ["traer los datos del tpv cada mes", "plan-importar-mensual"],
  ["sincronizar con tpv 123 automaticamente", "plan-importar-mensual"],
  ["por que no me contesta el asistente", "plan-asistente"],
  ["tengo el asistente incluido", "plan-asistente"],
  ["puedo hacer facturas", "no-hace-facturas"],
  ["sacar un ticket", "no-hace-facturas"],
  ["cobrar con tarjeta en la web", "no-cobra-tarjeta"],
  ["que paguen online al reservar", "no-cobra-tarjeta"],
  ["que salga en el calendario de la clienta", "no-escribe-google"],
  ["sincronizar google en los dos sentidos", "no-escribe-google"],
  ["mandar la campaña a todas a la vez", "no-campanas-automaticas"],
  ["envio masivo de whatsapp", "no-campanas-automaticas"],

  // ── Dudas técnicas ───────────────────────────────────────────────────
  ["como creo una cita", "tec-crear-cita"],
  ["como apunto una cita nueva", "tec-crear-cita"],
  ["como cambio una cita de dia", "tec-mover-cita"],
  ["mover una cita a otra hora", "tec-mover-cita"],
  ["como acepto una reserva", "tec-confirmar"],
  ["donde confirmo las solicitudes", "tec-confirmar"],
  ["como anulo una cita", "tec-cancelar"],
  ["como borro una cita", "tec-cancelar"],
  ["donde apunto la formula del color", "tec-anotar-color"],
  ["como guardo el tinte de una clienta", "tec-anotar-color"],
  ["como importo el excel del tpv", "tec-importar-tpv"],
  ["traer las clientas del tpv", "tec-importar-tpv"],
  ["como activo la señal", "tec-senal"],
  ["como pido un bizum de señal", "tec-senal"],
  ["como cambio el horario", "tec-horario"],
  ["como cierro un dia por vacaciones", "tec-horario"],
  ["como cambio el precio de un servicio", "tec-precios"],
  ["añadir un servicio nuevo", "tec-precios"],
  ["no me llegan reservas", "tec-no-llegan-reservas"],
  ["nadie reserva por la web", "tec-no-llegan-reservas"],
  ["no encuentro una cita", "tec-no-sale-cita"],
  ["no me aparece la cita", "tec-no-sale-cita"],
  ["no se abre whatsapp", "tec-whatsapp-no-abre"],
  ["el whatsapp no manda nada", "tec-whatsapp-no-abre"],
  ["va muy lento", "tec-panel-lento"],
  ["se queda cargando todo el rato", "tec-panel-lento"],
  ["no puedo entrar al panel", "tec-contrasena"],
  ["he olvidado la contraseña", "tec-contrasena"],

  // ── Fuera del dominio ────────────────────────────────────────────────
  ["que tiempo hace mañana", "no-se"],
  ["quien gano el partido", "no-se"],
  ["receta de tortilla de patatas", "no-se"],
  ["capital de francia", "no-se"],
  ["pon musica", "no-se"],
  ["cuanto es 2 mas 2", "no-se"],
  ["traduce hola al ingles", "no-se"],
  ["noticias de hoy", "no-se"],
  ["el precio de la luz", "no-se"],
  ["horoscopo de leo", "no-se"],
  ["xyzzy", "no-se"],
  ["asdf qwer", "no-se"],
];
