/** Un resolutor por intención de negocio (ids exactos de la especificación). */
import * as agenda from "./agenda";
import * as clientas from "./clientas";
import * as configuracion from "./configuracion";
import * as dinero from "./dinero";
import * as equipo from "./equipo";
import * as hoy from "./hoy";
import * as marketing from "./marketing";
import * as senal from "./senal";
import * as servicios from "./servicios";
import type { Resolutor } from "./tipos";

export const RESOLUTORES: Record<string, Resolutor> = {
  "citas-hoy": hoy.citasHoy,
  "citas-hoy-profesional": hoy.citasHoyProfesional,
  "proxima-cita": hoy.proximaCita,
  "lista-citas-hoy": hoy.listaCitasHoy,
  "huecos-hoy": hoy.huecosHoy,
  "ocupacion-hoy": hoy.ocupacionHoy,
  "ingresos-hoy": hoy.ingresosHoy,
  "pendiente-de-ti": hoy.pendienteDeTi,
  "solicitudes-pendientes": hoy.solicitudesPendientes,
  "por-marcar": hoy.porMarcar,
  "abierto-ahora": configuracion.abiertoAhora,
  "colores-hoy": hoy.coloresHoy,
  "citas-dia": agenda.citasDia,
  "citas-manana": agenda.citasManana,
  "huecos-dia": agenda.huecosDia,
  "primer-hueco-servicio": agenda.primerHuecoServicio,
  "hueco-profesional": agenda.huecoProfesional,
  "citas-periodo": agenda.citasPeriodo,
  "ocupacion-periodo": agenda.ocupacionPeriodo,
  "proxima-cita-clienta": agenda.proximaCitaClienta,
  "recordatorios-manana": agenda.recordatoriosManana,
  "lista-espera": agenda.listaEspera,
  "franja-floja": agenda.franjaFloja,
  "dia-mas-lleno": agenda.diaMasLleno,
  cancelaciones: agenda.cancelaciones,
  plantones: agenda.plantones,
  "ultima-visita-clienta": clientas.ultimaVisitaClienta,
  "ultimo-color-clienta": clientas.ultimoColorClienta,
  "frecuencia-clienta": clientas.frecuenciaClienta,
  "gasto-clienta": clientas.gastoClienta,
  "datos-clienta": clientas.datosClienta,
  "notas-clienta": clientas.notasClienta,
  "clientas-total": clientas.clientasTotal,
  "clientas-nuevas": clientas.clientasNuevas,
  "clientas-recurrentes": clientas.clientasRecurrentes,
  "clientas-inactivas": clientas.clientasInactivas,
  "mejores-clientas": clientas.mejoresClientas,
  "color-pendiente": clientas.colorPendiente,
  cumpleanos: clientas.cumpleanos,
  "clientas-con-deuda": clientas.clientasConDeuda,
  "clienta-bloqueada": clientas.clientaBloqueada,
  "buscar-clienta": clientas.buscarClienta,
  "horario-profesional": equipo.horarioProfesional,
  "quien-trabaja": equipo.quienTrabaja,
  "citas-profesional-periodo": equipo.citasProfesionalPeriodo,
  "ocupacion-profesional": equipo.ocupacionProfesional,
  "dinero-profesional": dinero.dineroProfesional,
  "lo-que-mas-hace": equipo.loQueMasHace,
  "profesional-habitual": equipo.profesionalHabitual,
  "precio-servicio": servicios.precioServicio,
  "duracion-servicio": servicios.duracionServicio,
  "servicio-mas-pedido": servicios.servicioMasPedido,
  "servicio-mas-rentable": servicios.servicioMasRentable,
  carta: servicios.carta,
  "veces-servicio": servicios.vecesServicio,
  "cobrado-periodo": dinero.cobradoPeriodo,
  "previsto-periodo": dinero.previstoPeriodo,
  "estimacion-mes": dinero.estimacionMes,
  "cobro-por-metodo": dinero.cobroPorMetodo,
  "comparar-periodos": dinero.compararPeriodos,
  "precio-medio": dinero.precioMedio,
  "dinero-servicio": servicios.dineroServicio,
  "resumen-mes": dinero.resumenMes,
  "senales-pendientes": senal.senalesPendientes,
  "senales-vencidas": senal.senalesVencidas,
  "senal-cita": senal.senalCita,
  "regla-senal": senal.reglaSenal,
  "senales-recibidas": senal.senalesRecibidas,
  campanas: marketing.campanas,
  recuperables: marketing.recuperables,
  "huecos-flojos": marketing.huecosFlojos,
  "segunda-visita": marketing.segundaVisita,
  resenas: marketing.resenas,
  "horario-salon": configuracion.horarioSalon,
  "enlace-reservas": configuracion.enlaceReservas,
  "politica-cancelacion": configuracion.politicaCancelacion,
  "preguntas-reserva": configuracion.preguntasReserva,
  "plantones-config": configuracion.plantonesConfig,
  "mensajes-whatsapp": configuracion.mensajesWhatsapp,
  "duracion-flexible": configuracion.duracionFlexible,
  "calendario-suscrito": configuracion.calendarioSuscrito,
  "equipo-y-colores": configuracion.equipoYColores,
  "que-puedo-preguntar": configuracion.quePuedoPreguntar,
  "como-preguntar": configuracion.comoPreguntar,
};
