/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SSalonSlugRouteImport } from './routes/s.$salonSlug'
import { Route as AppWaitlistRouteImport } from './routes/app.waitlist'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppServicesRouteImport } from './routes/app.services'
import { Route as AppMarketingRouteImport } from './routes/app.marketing'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppEmployeesRouteImport } from './routes/app.employees'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppAppointmentsRouteImport } from './routes/app.appointments'
import { Route as SSalonSlugIndexRouteImport } from './routes/s.$salonSlug.index'
import { Route as SSalonSlugConfirmationRouteImport } from './routes/s.$salonSlug.confirmation'
import { Route as SSalonSlugBookRouteImport } from './routes/s.$salonSlug.book'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SSalonSlugRoute = SSalonSlugRouteImport.update({
  id: '/s/$salonSlug',
  path: '/s/$salonSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWaitlistRoute = AppWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const SSalonSlugIndexRoute = SSalonSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SSalonSlugRoute,
} as any)
const SSalonSlugConfirmationRoute = SSalonSlugConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => SSalonSlugRoute,
} as any)
const SSalonSlugBookRoute = SSalonSlugBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => SSalonSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/waitlist': typeof AppWaitlistRoute
  '/s/$salonSlug': typeof SSalonSlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/s/$salonSlug/book': typeof SSalonSlugBookRoute
  '/s/$salonSlug/confirmation': typeof SSalonSlugConfirmationRoute
  '/s/$salonSlug/': typeof SSalonSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/waitlist': typeof AppWaitlistRoute
  '/app': typeof AppIndexRoute
  '/s/$salonSlug/book': typeof SSalonSlugBookRoute
  '/s/$salonSlug/confirmation': typeof SSalonSlugConfirmationRoute
  '/s/$salonSlug': typeof SSalonSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/waitlist': typeof AppWaitlistRoute
  '/s/$salonSlug': typeof SSalonSlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/s/$salonSlug/book': typeof SSalonSlugBookRoute
  '/s/$salonSlug/confirmation': typeof SSalonSlugConfirmationRoute
  '/s/$salonSlug/': typeof SSalonSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/app/appointments'
    | '/app/calendar'
    | '/app/clients'
    | '/app/employees'
    | '/app/insights'
    | '/app/marketing'
    | '/app/services'
    | '/app/settings'
    | '/app/waitlist'
    | '/s/$salonSlug'
    | '/app/'
    | '/s/$salonSlug/book'
    | '/s/$salonSlug/confirmation'
    | '/s/$salonSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/app/appointments'
    | '/app/calendar'
    | '/app/clients'
    | '/app/employees'
    | '/app/insights'
    | '/app/marketing'
    | '/app/services'
    | '/app/settings'
    | '/app/waitlist'
    | '/app'
    | '/s/$salonSlug/book'
    | '/s/$salonSlug/confirmation'
    | '/s/$salonSlug'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/app/appointments'
    | '/app/calendar'
    | '/app/clients'
    | '/app/employees'
    | '/app/insights'
    | '/app/marketing'
    | '/app/services'
    | '/app/settings'
    | '/app/waitlist'
    | '/s/$salonSlug'
    | '/app/'
    | '/s/$salonSlug/book'
    | '/s/$salonSlug/confirmation'
    | '/s/$salonSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SSalonSlugRoute: typeof SSalonSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/s/$salonSlug': {
      id: '/s/$salonSlug'
      path: '/s/$salonSlug'
      fullPath: '/s/$salonSlug'
      preLoaderRoute: typeof SSalonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/waitlist': {
      id: '/app/waitlist'
      path: '/waitlist'
      fullPath: '/app/waitlist'
      preLoaderRoute: typeof AppWaitlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services': {
      id: '/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketing': {
      id: '/app/marketing'
      path: '/marketing'
      fullPath: '/app/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees': {
      id: '/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments': {
      id: '/app/appointments'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/s/$salonSlug/': {
      id: '/s/$salonSlug/'
      path: '/'
      fullPath: '/s/$salonSlug/'
      preLoaderRoute: typeof SSalonSlugIndexRouteImport
      parentRoute: typeof SSalonSlugRoute
    }
    '/s/$salonSlug/confirmation': {
      id: '/s/$salonSlug/confirmation'
      path: '/confirmation'
      fullPath: '/s/$salonSlug/confirmation'
      preLoaderRoute: typeof SSalonSlugConfirmationRouteImport
      parentRoute: typeof SSalonSlugRoute
    }
    '/s/$salonSlug/book': {
      id: '/s/$salonSlug/book'
      path: '/book'
      fullPath: '/s/$salonSlug/book'
      preLoaderRoute: typeof SSalonSlugBookRouteImport
      parentRoute: typeof SSalonSlugRoute
    }
  }
}

interface AppRouteChildren {
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppClientsRoute: typeof AppClientsRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWaitlistRoute: typeof AppWaitlistRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppClientsRoute: AppClientsRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWaitlistRoute: AppWaitlistRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SSalonSlugRouteChildren {
  SSalonSlugBookRoute: typeof SSalonSlugBookRoute
  SSalonSlugConfirmationRoute: typeof SSalonSlugConfirmationRoute
  SSalonSlugIndexRoute: typeof SSalonSlugIndexRoute
}

const SSalonSlugRouteChildren: SSalonSlugRouteChildren = {
  SSalonSlugBookRoute: SSalonSlugBookRoute,
  SSalonSlugConfirmationRoute: SSalonSlugConfirmationRoute,
  SSalonSlugIndexRoute: SSalonSlugIndexRoute,
}

const SSalonSlugRouteWithChildren = SSalonSlugRoute._addFileChildren(
  SSalonSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SSalonSlugRoute: SSalonSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
